"""Hardcoded jurisdiction list for CourtListener search."""

# Organized by optgroup for the dropdown
JURISDICTIONS = {
    "Federal": [
        ("scotus", "U.S. Supreme Court"),
        ("ca1", "First Circuit"),
        ("ca2", "Second Circuit"),
        ("ca3", "Third Circuit"),
        ("ca4", "Fourth Circuit"),
        ("ca5", "Fifth Circuit"),
        ("ca6", "Sixth Circuit"),
        ("ca7", "Seventh Circuit"),
        ("ca8", "Eighth Circuit"),
        ("ca9", "Ninth Circuit"),
        ("ca10", "Tenth Circuit"),
        ("ca11", "Eleventh Circuit"),
        ("cadc", "D.C. Circuit"),
        ("cafc", "Federal Circuit"),
    ],
    "State Supreme Courts": [
        ("ala", "Alabama Supreme Court"),
        ("alaska", "Alaska Supreme Court"),
        ("ariz", "Arizona Supreme Court"),
        ("ark", "Arkansas Supreme Court"),
        ("cal", "California Supreme Court"),
        ("colo", "Colorado Supreme Court"),
        ("conn", "Connecticut Supreme Court"),
        ("del", "Delaware Supreme Court"),
        ("fla", "Florida Supreme Court"),
        ("ga", "Georgia Supreme Court"),
        ("haw", "Hawaii Supreme Court"),
        ("idaho", "Idaho Supreme Court"),
        ("ill", "Illinois Supreme Court"),
        ("ind", "Indiana Supreme Court"),
        ("iowa", "Iowa Supreme Court"),
        ("kan", "Kansas Supreme Court"),
        ("ky", "Kentucky Supreme Court"),
        ("la", "Louisiana Supreme Court"),
        ("me", "Maine Supreme Judicial Court"),
        ("md", "Maryland Court of Appeals"),
        ("mass", "Massachusetts Supreme Judicial Court"),
        ("mich", "Michigan Supreme Court"),
        ("minn", "Minnesota Supreme Court"),
        ("miss", "Mississippi Supreme Court"),
        ("mo", "Missouri Supreme Court"),
        ("mont", "Montana Supreme Court"),
        ("neb", "Nebraska Supreme Court"),
        ("nev", "Nevada Supreme Court"),
        ("nh", "New Hampshire Supreme Court"),
        ("nj", "New Jersey Supreme Court"),
        ("nm", "New Mexico Supreme Court"),
        ("ny", "New York Court of Appeals"),
        ("nc", "North Carolina Supreme Court"),
        ("nd", "North Dakota Supreme Court"),
        ("ohio", "Ohio Supreme Court"),
        ("okla", "Oklahoma Supreme Court"),
        ("or", "Oregon Supreme Court"),
        ("pa", "Pennsylvania Supreme Court"),
        ("ri", "Rhode Island Supreme Court"),
        ("sc", "South Carolina Supreme Court"),
        ("sd", "South Dakota Supreme Court"),
        ("tenn", "Tennessee Supreme Court"),
        ("tex", "Texas Supreme Court"),
        ("utah", "Utah Supreme Court"),
        ("vt", "Vermont Supreme Court"),
        ("va", "Virginia Supreme Court"),
        ("wash", "Washington Supreme Court"),
        ("wva", "West Virginia Supreme Court of Appeals"),
        ("wis", "Wisconsin Supreme Court"),
        ("wyo", "Wyoming Supreme Court"),
    ],
    "State Appellate Courts": [
        ("alactapp", "Alabama Court of Civil Appeals"),
        ("alacrimapp", "Alabama Court of Criminal Appeals"),
        ("alaskactapp", "Alaska Court of Appeals"),
        ("arizctapp", "Arizona Court of Appeals"),
        ("arkctapp", "Arkansas Court of Appeals"),
        ("calctapp", "California Court of Appeal"),
        ("coloctapp", "Colorado Court of Appeals"),
        ("connappct", "Connecticut Appellate Court"),
        ("flactapp", "Florida District Court of Appeal"),
        ("gactapp", "Georgia Court of Appeals"),
        ("hawctapp", "Hawaii Intermediate Court of Appeals"),
        ("idahoctapp", "Idaho Court of Appeals"),
        ("illappct", "Illinois Appellate Court"),
        ("indctapp", "Indiana Court of Appeals"),
        ("iowactapp", "Iowa Court of Appeals"),
        ("kanctapp", "Kansas Court of Appeals"),
        ("kyctapp", "Kentucky Court of Appeals"),
        ("lactapp", "Louisiana Court of Appeal"),
        ("mdctspecapp", "Maryland Court of Special Appeals"),
        ("massappct", "Massachusetts Appeals Court"),
        ("michctapp", "Michigan Court of Appeals"),
        ("minnctapp", "Minnesota Court of Appeals"),
        ("missctapp", "Mississippi Court of Appeals"),
        ("moctapp", "Missouri Court of Appeals"),
        ("nebctapp", "Nebraska Court of Appeals"),
        ("nevapp", "Nevada Court of Appeals"),
        ("njsuperctappdiv", "New Jersey Superior Court, Appellate Division"),
        ("nyappterm", "New York Appellate Term"),
        ("nyappdiv", "New York Appellate Division"),
        ("ncctapp", "North Carolina Court of Appeals"),
        ("ndctapp", "North Dakota Court of Appeals"),
        ("ohioctapp", "Ohio Court of Appeals"),
        ("oklacivapp", "Oklahoma Court of Civil Appeals"),
        ("oklacrimapp", "Oklahoma Court of Criminal Appeals"),
        ("orctapp", "Oregon Court of Appeals"),
        ("pasuperct", "Pennsylvania Superior Court"),
        ("pacommwct", "Pennsylvania Commonwealth Court"),
        ("scctapp", "South Carolina Court of Appeals"),
        ("tennctapp", "Tennessee Court of Appeals"),
        ("tenncrimapp", "Tennessee Court of Criminal Appeals"),
        ("texapp", "Texas Court of Appeals"),
        ("texcrimapp", "Texas Court of Criminal Appeals"),
        ("utahctapp", "Utah Court of Appeals"),
        ("vactapp", "Virginia Court of Appeals"),
        ("washctapp", "Washington Court of Appeals"),
        ("wisctapp", "Wisconsin Court of Appeals"),
    ],
}

# Flat list for validation
ALL_JURISDICTIONS = {}
for group_courts in JURISDICTIONS.values():
    for court_id, display_name in group_courts:
        ALL_JURISDICTIONS[court_id] = display_name
