# Generated by Django 4.2.30 on 2026-08-04 18:20

import apps.drafts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matters', '0050_historicalproceeding_drive_folder_and_more'),
        ('case', '0073_conversation_kind_conversation_research_depth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_file_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('drive_path', models.CharField(blank=True, max_length=500)),
                ('drive_modified', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('published', 'Published'), ('abandoned', 'Abandoned')], default='drafting', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_session', to='case.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sessions', to='matters.matter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('odt_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.drafts.models.draft_file_path)),
                ('pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.drafts.models.draft_file_path)),
                ('facsimile', models.TextField(blank=True)),
                ('edits', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='drafts.draftsession')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddConstraint(
            model_name='draftversion',
            constraint=models.UniqueConstraint(fields=('session', 'seq'), name='unique_draft_version_seq'),
        ),
    ]
