# Generated by Django 4.2.30 on 2026-08-06 11:29

import apps.drafts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsession',
            name='companion_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftsession',
            name='companion_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='draftsession',
            name='companion_text_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.drafts.models._new_token_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edits', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('edit_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_rounds', to='drafts.draftsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
