# Generated by Django 4.2.26 on 2025-12-18 13:20
# Migration to move Note model from case app to notes app.
# State-only because the table is created by case.0025_add_note_model

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matters", "0027_add_proceeding_nickname"),
        ("case", "0027_delete_note"),
    ]

    operations = [
        # State-only: the table already exists from case.0025_add_note_model
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Note",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        (
                            "category",
                            models.CharField(
                                choices=[
                                    ("analysis", "Analysis"),
                                    ("drafting", "Drafting"),
                                    ("interview", "Interview"),
                                    ("issue", "Issue"),
                                    ("note", "Note"),
                                ],
                                default="note",
                                max_length=20,
                            ),
                        ),
                        (
                            "date",
                            models.DateField(default=django.utils.timezone.localdate),
                        ),
                        ("content", models.TextField(blank=True, default="")),
                        ("importance", models.PositiveIntegerField(default=5)),
                        ("viewed_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "documents",
                            models.ManyToManyField(
                                blank=True, related_name="notes", to="case.document"
                            ),
                        ),
                        (
                            "highlights",
                            models.ManyToManyField(
                                blank=True, related_name="notes", to="case.highlight"
                            ),
                        ),
                        (
                            "labels",
                            models.ManyToManyField(
                                blank=True, related_name="notes", to="case.label"
                            ),
                        ),
                        (
                            "matter",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="notes",
                                to="matters.matter",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="notes",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "app_note",
                        "ordering": ["-updated_at"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
