# Generated by Django 4.2.26 on 2025-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_make_matter_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="topic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                    ("interview", "Interview"),
                    ("issue", "Issue"),
                    ("note", "Note"),
                    ("research", "Research"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
