# Generated by Django 4.2.26 on 2025-12-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_add_research_category_and_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="date",
        ),
    ]
