# Generated by Django 4.2.26 on 2025-12-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0004_remove_date_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
