# Generated by Django 4.2.26 on 2026-02-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_note_created_by_note_updated_by_noteview_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnote",
            name="category",
            field=models.CharField(
                choices=[
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                    ("guide", "Guide"),
                    ("interview", "Interview"),
                    ("issue", "Issue"),
                    ("note", "Note"),
                    ("research", "Research"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                    ("guide", "Guide"),
                    ("interview", "Interview"),
                    ("issue", "Issue"),
                    ("note", "Note"),
                    ("research", "Research"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
