# Generated by Django 4.2.29 on 2026-03-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_add_notefolder_model_and_note_folder_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotefolder',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalnotefolder',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notes.notefolder'),
        ),
        migrations.AddField(
            model_name='notefolder',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='notes.notefolder'),
        ),
    ]
