# Generated by Django 4.2.29 on 2026-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_reset_importance_to_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnote',
            name='importance',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
