# Generated by Django 4.2.30 on 2026-08-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_historicalnote_ai_context_note_ai_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated abstract used for intelligent context selection'),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='summary_source_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalnotefolder',
            name='ai_library',
            field=models.BooleanField(default=False, help_text='Notes in this folder and its subfolders are offered to the matter AI'),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated abstract used for intelligent context selection'),
        ),
        migrations.AddField(
            model_name='note',
            name='summary_source_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='notefolder',
            name='ai_library',
            field=models.BooleanField(default=False, help_text='Notes in this folder and its subfolders are offered to the matter AI'),
        ),
    ]
