# Generated by Django 4.2.30 on 2026-08-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0050_historicalproceeding_drive_folder_and_more'),
        ('notes', '0020_historicalnote_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotefolder',
            name='matter',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Null = general tree; set = this matter's private tree", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='notefolder',
            name='matter',
            field=models.ForeignKey(blank=True, help_text="Null = general tree; set = this matter's private tree", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_folders', to='matters.matter'),
        ),
    ]
