# Generated by Django 4.2.30 on 2026-08-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_historicalnotefolder_matter_notefolder_matter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnote',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='historicalnote',
            name='drive_modified',
        ),
        migrations.RemoveField(
            model_name='historicalnote',
            name='drive_path',
        ),
        migrations.RemoveField(
            model_name='historicalnote',
            name='drive_synced_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='drive_modified',
        ),
        migrations.RemoveField(
            model_name='note',
            name='drive_path',
        ),
        migrations.RemoveField(
            model_name='note',
            name='drive_synced_at',
        ),
    ]
