# Generated by Django 4.2.30 on 2026-08-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_remove_historicalnote_drive_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnote',
            name='ai_context',
        ),
        migrations.RemoveField(
            model_name='historicalnotefolder',
            name='ai_library',
        ),
        migrations.RemoveField(
            model_name='note',
            name='ai_context',
        ),
        migrations.RemoveField(
            model_name='notefolder',
            name='ai_library',
        ),
    ]
