# Generated by Django 4.2.30 on 2026-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_remove_historicalnote_ai_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='ai_write_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='ai_write_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
