# Generated by Django 3.2.6 on 2022-11-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                ("date", models.DateField(null=True)),
                ("actions", models.TextField(null=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, max_digits=3, null=True),
                ),
                ("contractor_rate", models.IntegerField(blank=True, null=True)),
                ("firm_rate", models.IntegerField(null=True)),
                ("comp", models.IntegerField(blank=True, null=True)),
                ("entered", models.IntegerField(blank=True, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "db_table": "app_activity",
            },
        ),
    ]
