# Generated by Django 4.1.5 on 2023-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="hours",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
