# Generated by Django 4.2.14 on 2024-07-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoicing.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoicing.invoice",
            ),
        ),
    ]
