# Generated by Django 4.2.14 on 2024-07-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_alter_expenseentry_invoice_alter_timeentry_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeentry",
            name="contractor_rate",
        ),
    ]
