# Generated by Django 4.2.26 on 2025-11-24 17:42

from django.db import migrations


def populate_abbreviation_codes(apps, schema_editor):
    AbbreviationCode = apps.get_model("activity", "AbbreviationCode")

    # Existing abbreviations from the hardcoded dict in views.py
    codes_data = [
        ("attn ", "attention "),
        ("Attn ", "Attention "),
        ("mot ", "motion "),
        ("Mot ", "Motion "),
        ("Aff ", "Affidavit "),
        ("conf ", "conference "),
        ("Conf ", "Conference "),
        ("conf. ", "conference "),
        ("Conf. ", "Conference "),
        (" resp ", " response "),
        (" Resp ", " Response "),
        (" opp ", " opposition "),
        (" Opp ", " Opposition "),
        (" vm ", " voicemail "),
        (" vm.", " voicemail."),
        ("Vm ", "Voicemail "),
        (" Vm.", " Left voicemail."),
        ("dep ", "deposition"),
        ("Dep ", "Deposition"),
        (" OC", " opposing counsel"),
        (" SMF", " Statement of Material Facts"),
        (" SM", " Special Master"),
        (" MSJ", " Motion for Summary Judgment"),
        (" MTD", " Motion to Dismiss"),
    ]

    abbreviations = [
        AbbreviationCode(code=code, expansion=expansion, is_active=True)
        for code, expansion in codes_data
    ]

    AbbreviationCode.objects.bulk_create(abbreviations)


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_abbreviationcode"),
    ]

    operations = [
        migrations.RunPython(populate_abbreviation_codes),
    ]
