# Generated by Django 4.1.5 on 2023-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_alter_timeentry_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="hours",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
