# Generated by Django 4.2.14 on 2024-07-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_remove_timeentry_contractor_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeentry",
            old_name="firm_rate",
            new_name="rate",
        ),
    ]
