# Generated by Django 4.1.5 on 2024-02-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matters", "0002_matter_contacts"),
        ("activity", "0003_alter_timeentry_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                ("date", models.DateField(null=True)),
                ("description", models.TextField(null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("comp", models.IntegerField(blank=True, null=True)),
                ("entered", models.IntegerField(blank=True, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "db_table": "app_expenses",
            },
        ),
    ]
