# Generated by Django 4.2.26 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_populate_abbreviation_codes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expenseentry",
            index=models.Index(fields=["date"], name="app_expense_date_d2e25c_idx"),
        ),
        migrations.AddIndex(
            model_name="expenseentry",
            index=models.Index(
                fields=["matter"], name="app_expense_matter__1db86f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["date"], name="app_activit_date_0ff7e3_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(
                fields=["matter"], name="app_activit_matter__846e74_idx"
            ),
        ),
    ]
