# Generated by Django 5.0.4 on 2024-06-13 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_alter_timeentry_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeentry",
            old_name="user_id",
            new_name="user",
        ),
    ]
