# Generated by Django 5.0.4 on 2024-06-13 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0007_alter_expenseentry_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expenseentry",
            old_name="user_id",
            new_name="user",
        ),
    ]
