# Generated by Django 5.0.4 on 2024-06-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0008_rename_user_id_expenseentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentry",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
