# Generated by Django 5.0.4 on 2024-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0009_expenseentry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentry",
            name="invoice",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="invoice",
            field=models.IntegerField(null=True),
        ),
    ]
