# Generated by Django 4.2.29 on 2026-07-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matters", "0043_backfill_client_relationships"),
        ("activity", "0010_historicalflatfeeentry_flatfeeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylabel",
            name="claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitylabel",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_labels",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="activitylabel",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalactivitylabel",
            name="claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalactivitylabel",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="historicalactivitylabel",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activitylabel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalactivitylabel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="activitylabel",
            constraint=models.UniqueConstraint(
                fields=("matter", "name"),
                name="uniq_label_name_per_matter",
                violation_error_message="This matter already has a label with this name.",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylabel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("matter__isnull", True)),
                fields=("name",),
                name="uniq_global_label_name",
                violation_error_message="A label with this name already exists.",
            ),
        ),
    ]
