# Generated by Django 4.2.29 on 2026-07-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_categories_rebuild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='historicalactivitycategory',
            name='color',
        ),
    ]
