# Generated by Django 4.2.29 on 2026-07-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_remove_activitycategory_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='claimed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalactivitycategory',
            name='claimed',
            field=models.BooleanField(default=True),
        ),
    ]
