# Generated by Django 3.2.6 on 2022-11-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("type", models.CharField(max_length=10, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=9, null=True),
                ),
                ("entered", models.IntegerField(blank=True, null=True)),
                ("confirmed", models.IntegerField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "db_table": "app_trust",
            },
        ),
    ]
