# Generated by Django 4.2.29 on 2026-06-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_transaction_created_at_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='processor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='processor_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='processor_txn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processor_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processor_txn_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
