# Generated by Django 4.2.29 on 2026-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_historicaltransaction_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='method',
            field=models.CharField(blank=True, choices=[('ACH', 'ACH'), ('Card', 'Card'), ('Wire', 'Wire'), ('Transfer', 'Transfer'), ('Check', 'Check')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('ACH', 'ACH'), ('Card', 'Card'), ('Wire', 'Wire'), ('Transfer', 'Transfer'), ('Check', 'Check')], default='', max_length=10),
        ),
    ]
