# Generated by Django 4.2.26 on 2025-12-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0027_add_proceeding_nickname"),
        ("outlines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outlines",
                to="matters.matter",
            ),
        ),
    ]
