# Generated by Django 4.2.26 on 2025-12-07 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0003_add_importance"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="outline",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
