# Generated by Django 4.2.26 on 2025-12-07 12:50

from django.db import migrations


def populate_date_from_created_at(apps, schema_editor):
    """Set date field to created_at date for existing outlines."""
    Outline = apps.get_model("outlines", "Outline")
    for outline in Outline.objects.all():
        outline.date = outline.created_at.date()
        outline.save(update_fields=["date"])


def reverse_populate(apps, schema_editor):
    """No-op reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0004_add_date_and_viewed_at"),
    ]

    operations = [
        migrations.RunPython(populate_date_from_created_at, reverse_populate),
    ]
