# Generated by Django 4.2.26 on 2025-12-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0005_populate_date_from_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outline",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="outlineitem",
            name="heading",
            field=models.BooleanField(default=False),
        ),
    ]
