# Generated by Django 4.2.26 on 2025-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0008_add_sources_to_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("issues", "Issues"),
                    ("interviews", "Interviews"),
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
