# Generated by Django 4.2.26 on 2025-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0009_add_category_to_outline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="category",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("issue", "Issue"),
                    ("interview", "Interview"),
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
