# Generated by Django 4.2.26 on 2025-12-10 11:24

from django.db import migrations


def move_headings_to_top_level(apps, schema_editor):
    """Move heading items with parents to top level (parent=None)."""
    OutlineItem = apps.get_model("outlines", "OutlineItem")

    # Find all heading items that have a parent
    heading_items = OutlineItem.objects.filter(heading=True, parent__isnull=False)

    for item in heading_items:
        # Get the max order at the root level for this outline
        root_items = OutlineItem.objects.filter(outline=item.outline, parent__isnull=True)
        max_order = root_items.order_by("-order").values_list("order", flat=True).first()
        new_order = (max_order or 0) + 1

        # Move to root level
        item.parent = None
        item.order = new_order
        item.save()


def reverse_migration(apps, schema_editor):
    """No reverse - we can't know what the original parent was."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0010_change_category_default"),
    ]

    operations = [
        migrations.RunPython(move_headings_to_top_level, reverse_migration),
    ]
