# Generated by Django 4.2.26 on 2025-12-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0015_heading_integer_to_boolean"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="sources_display",
            field=models.CharField(
                choices=[("citation", "Citation"), ("icon", "Icon"), ("hide", "Hide")],
                default="citation",
                max_length=10,
            ),
        ),
    ]
