# Generated by Django 4.2.26 on 2025-12-12 15:06

from django.db import migrations, models


def update_citation_to_show(apps, schema_editor):
    Outline = apps.get_model("outlines", "Outline")
    Outline.objects.filter(sources_display="citation").update(sources_display="show")


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0016_add_sources_display"),
    ]

    operations = [
        migrations.RunPython(update_citation_to_show, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="outline",
            name="sources_display",
            field=models.CharField(
                choices=[
                    ("show", "Show Sources"),
                    ("hide", "Hide"),
                    ("icon", "Icon Only"),
                ],
                default="show",
                max_length=10,
            ),
        ),
    ]
