# Generated by Django 4.2.29 on 2026-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_convert_priority_1_to_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
