# Generated by Django 4.2.15 on 2024-09-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="symbol",
            new_name="initials",
        ),
    ]
