# Generated by Django 4.2.15 on 2024-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_symbol_customuser_initials"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User")],
                default="USER",
                max_length=5,
            ),
        ),
    ]
