# Generated by Django 4.2.26 on 2026-02-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_historicalcustomuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="digest_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="digest_include_weekends",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="digest_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="digest_include_weekends",
            field=models.BooleanField(default=False),
        ),
    ]
