# Generated by Django 4.2.28 on 2026-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_perm_all_matters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="perm_research",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="perm_research",
            field=models.BooleanField(default=True),
        ),
    ]
