# Generated by Django 4.2.29 on 2026-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_perm_research_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nav_layout',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='nav_layout',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20),
        ),
    ]
