# Generated by Django 4.2.29 on 2026-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_nav_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
