# Generated by Django 4.2.30 on 2026-08-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_title_historicalcustomuser_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tasks_layout',
            field=models.CharField(choices=[('classic', 'Classic'), ('panel', 'Matters panel')], default='classic', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='tasks_layout',
            field=models.CharField(choices=[('classic', 'Classic'), ('panel', 'Matters panel')], default='classic', max_length=20),
        ),
    ]
