# Generated by Django 4.2.30 on 2026-08-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_tasks_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task_user_chips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='task_user_chips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
