# Generated by Django 4.2.30 on 2026-08-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_task_user_chips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tasks_layout',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='tasks_layout',
        ),
    ]
