exclude: .*migrations\/.*

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: [ --profile, black, --combine-as, --trailing-comma ]
        language_version: python3.13

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-django
        language_version: python3.13
        args: [ --profile, django ]
        exclude: "templates/emails/"
      - id: djlint-reformat-django
        files: "\\.html"
        language_version: python3.13
        args: [ --profile, django ]
        exclude: "templates/emails/"

  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: ./node_modules/.bin/stylelint --fix
        language: system
        files: "static/css/.*\\.css$"
        exclude: "(dropzone|lucide)\\.css$"
