# Generated by Django 4.2.15 on 2024-09-06 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CHECK", "Check"),
                            ("CARD", "Card"),
                            ("TRUST", "Trust"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matters.matter"
                    ),
                ),
            ],
            options={
                "db_table": "app_billing_payment",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["matter"], name="app_billing_matter__f043b6_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_limit", models.DateField()),
                ("date_issued", models.DateField()),
                ("message", models.TextField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("show_comp", models.BooleanField(default=False)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "db_table": "app_billing_invoice",
                "indexes": [
                    models.Index(
                        fields=["matter"], name="app_billing_matter__ead650_idx"
                    )
                ],
            },
        ),
    ]
