# Generated by Django 4.2.16 on 2024-11-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
