# Generated by Django 4.2.14 on 2024-07-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_remove_invoice_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("CANCELED", "Canceled"),
                    ("APPROVED", "Approved"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
