# Generated by Django 4.2.14 on 2024-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="date_from",
        ),
    ]
