# Generated by Django 4.2.14 on 2024-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_rename_date_to_invoice_date_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
