# Generated by Django 4.2.14 on 2024-08-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_invoice_pdf_file"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="billing_inv_matter__fbb791_idx",
            old_name="invoicing_i_matter__1368ac_idx",
        ),
    ]
