# Generated by Django 4.2.14 on 2024-08-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0010_rename_invoicing_i_matter__1368ac_idx_billing_inv_matter__fbb791_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                    ("CANCELED", "Canceled"),
                    ("PAID", "Paid"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
