# Generated by Django 4.2.14 on 2024-08-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0003_rename_ref_no_matter_client_reference_id_and_more"),
        ("billing", "0011_alter_invoice_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CHECK", "Check"),
                            ("CARD", "Card"),
                            ("TRUST", "Trust"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matters.matter"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["matter"], name="billing_pay_matter__6084e8_idx"
                    )
                ],
            },
        ),
    ]
