# Generated by Django 4.2.15 on 2024-08-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_payment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="app_billing_matter__ead650_idx",
            old_name="billing_inv_matter__fbb791_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="app_billing_matter__f043b6_idx",
            old_name="billing_pay_matter__6084e8_idx",
        ),
        migrations.AlterModelTable(
            name="invoice",
            table="app_billing_invoice",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="app_billing_payment",
        ),
    ]
