# Generated by Django 4.2.15 on 2024-09-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0013_rename_billing_inv_matter__fbb791_idx_app_billing_matter__ead650_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                    ("CANCELED", "Canceled"),
                    ("PAID", "Paid"),
                    ("WAIVED", "Waived"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
