# Generated by Django 4.2.15 on 2024-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                    ("PAID", "Paid"),
                    ("WAIVED", "Waived"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
