# Generated by Django 3.2.6 on 2022-11-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("folders", "0001_initial"),
        ("intakes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone1", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone1_label",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("phone2", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone2_label",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("phone3", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone3_label",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("map", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("google_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "folder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="folders.folder",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intakes.intake",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_contact",
            },
        ),
    ]
