# Generated by Django 4.2.26 on 2025-11-25 11:09

import os
from datetime import datetime

from django.db import migrations


def normalize_phone_value(value):
    """
    Normalize phone to raw digits with optional extension.
    Returns (normalized_value, is_valid).
    """
    if not value:
        return value, True

    value = value.strip()

    # Extract extension if present
    extension = ""
    ext_patterns = [" x", " ext", " ext.", ","]
    lower = value.lower()
    for pattern in ext_patterns:
        if pattern in lower:
            idx = lower.index(pattern)
            ext_part = value[idx:].lower()
            # Extract just the digits from extension
            ext_digits = "".join(c for c in ext_part if c.isdigit())
            if ext_digits:
                extension = f"x{ext_digits}"
            value = value[:idx]
            break

    # Strip all non-numeric characters
    digits = "".join(c for c in value if c.isdigit())

    # Handle +1 country code
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]

    # Validate: must be exactly 10 digits
    if len(digits) == 10:
        return digits + extension, True

    # Invalid - return original
    return value.strip() + (" " + extension if extension else ""), False


def normalize_phone_data(apps, schema_editor):
    """Normalize existing phone data to raw digits."""
    Contact = apps.get_model("contacts", "Contact")
    Intake = apps.get_model("intakes", "Intake")

    invalid_phones = []

    # Normalize Contact phones
    for contact in Contact.objects.all():
        changed = False
        for field in ["phone1", "phone2", "phone3"]:
            value = getattr(contact, field)
            if value:
                normalized, is_valid = normalize_phone_value(value)
                if is_valid and normalized != value:
                    setattr(contact, field, normalized)
                    changed = True
                elif not is_valid:
                    invalid_phones.append(f"Contact {contact.id} {field}: {value}")
        if changed:
            contact.save()

    # Normalize Intake phones
    for intake in Intake.objects.all():
        if intake.phone:
            normalized, is_valid = normalize_phone_value(intake.phone)
            if is_valid and normalized != intake.phone:
                intake.phone = normalized
                intake.save()
            elif not is_valid:
                invalid_phones.append(f"Intake {intake.id}: {intake.phone}")

    # Log invalid phones for manual review
    if invalid_phones:
        # Write to log file
        log_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "logs")
        log_file = os.path.join(log_dir, "invalid_phones.log")

        with open(log_file, "w") as f:
            f.write(f"Phone Normalization Migration - {datetime.now()}\n")
            f.write("=" * 50 + "\n")
            f.write("INVALID PHONES (not modified, manual review needed):\n")
            for phone in invalid_phones:
                f.write(f"  - {phone}\n")
            f.write("=" * 50 + "\n")

        # Also print to console
        print(f"\n{len(invalid_phones)} invalid phone(s) found.")
        print(f"See logs/invalid_phones.log for details.\n")


def reverse_migration(apps, schema_editor):
    """Reverse migration is a no-op - we don't want to un-normalize data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_email_to_emailfield"),
        ("intakes", "0008_email_to_emailfield"),
    ]

    operations = [
        migrations.RunPython(normalize_phone_data, reverse_migration),
    ]
