# Generated by Django 5.0.4 on 2024-06-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="client_status",
            field=models.CharField(default="Nonclient", max_length=100),
        ),
    ]
