# Generated by Django 4.2.26 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_add_email2"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["client_status"], name="app_contact_client__ed2592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["user"], name="app_contact_user_id_37c528_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["folder"], name="app_contact_folder__3b1e60_idx"
            ),
        ),
    ]
