# Generated by Django 4.2.30 on 2026-07-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0007_remove_contact_app_contact_client__ed2592_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('inverse_label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_contact_relationship_type',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContactRelationship',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('relationship_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.relationshiptype')),
                ('to_contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact relationship',
                'verbose_name_plural': 'historical contact relationships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='contacts.contact')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='contacts.relationshiptype')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_contact_relationship',
                'indexes': [models.Index(fields=['from_contact'], name='app_contact_from_co_6949a2_idx'), models.Index(fields=['to_contact'], name='app_contact_to_cont_d4f901_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contactrelationship',
            constraint=models.UniqueConstraint(fields=('from_contact', 'to_contact', 'relationship_type'), name='uniq_contact_relationship_edge'),
        ),
        migrations.AddConstraint(
            model_name='contactrelationship',
            constraint=models.CheckConstraint(check=models.Q(('from_contact', models.F('to_contact')), _negated=True), name='no_self_contact_relationship'),
        ),
    ]
