# Generated by Django 4.2.15 on 2024-09-06 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("practice_area", models.CharField(max_length=50, null=True)),
                ("source", models.CharField(max_length=50, null=True)),
                ("status", models.CharField(default="Open", max_length=50)),
            ],
            options={
                "db_table": "app_intake",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "intake",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intakes.intake",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_intake_note",
            },
        ),
    ]
