# Generated by Django 4.2.26 on 2025-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intakes", "0007_add_note_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
