# Generated by Django 4.2.30 on 2026-07-28 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0013_migrate_importance_to_normal'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_plain', models.TextField(blank=True)),
                ('stripped_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_emails', to='intakes.intake')),
            ],
            options={
                'db_table': 'app_inbound_email',
            },
        ),
    ]
