# Generated by Django 4.2.30 on 2026-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0014_inboundemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalintake',
            name='assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalintake',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intake',
            name='assessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
