# Generated by Django 4.2.30 on 2026-07-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0016_formtemplate_historicalformtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalformsubmission',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('SUBMITTED', 'Submitted'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalformsubmission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('SUBMITTED', 'Submitted'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=10),
        ),
    ]
