# Generated by Django 5.0.4 on 2024-06-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rate",
            field=models.IntegerField(default=400),
            preserve_default=False,
        ),
    ]
