# Generated by Django 5.0.4 on 2024-06-13 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="rate",
            new_name="user_rate",
        ),
    ]
