# Generated by Django 5.0.4 on 2024-06-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_rate_customuser_user_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
