# Generated by Django 4.2.26 on 2025-11-30 19:08

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matters", "0023_practicearea_and_data_migration"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("text", models.TextField()),
                ("page_number", models.PositiveIntegerField()),
                ("coordinates", models.JSONField()),
                ("color", models.CharField(default="#FFFF00", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ],
            options={
                "db_table": "app_document_highlight",
                "ordering": ["document", "page_number", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("not_applicable", "Not Applicable"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="app_documen_search__eb0200_gin"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="matter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="matters.matter",
            ),
        ),
        migrations.AddIndex(
            model_name="highlight",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="app_documen_search__039cca_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="highlight",
            index=models.Index(
                fields=["matter", "document"], name="app_documen_matter__56246d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="highlight",
            index=models.Index(
                fields=["document", "page_number"],
                name="app_documen_documen_c699da_idx",
            ),
        ),
    ]
