# Generated by Django 4.2.26 on 2025-11-30 19:38

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_add_ocr_and_highlights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="highlight",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
