# Generated by Django 4.2.22 on 2025-08-10 22:17

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_matter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to=apps.documents.models.document_upload_path
            ),
        ),
    ]
