# Generated by Django 4.2.26 on 2025-12-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_fix_search_vector_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("Correspondence", "Correspondence"),
                    ("Discovery", "Discovery"),
                    ("Evidence", "Evidence"),
                    ("Record", "Record"),
                ],
                default="Evidence",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("extracted", "Extracted"),
                    ("failed", "Failed"),
                    ("not_applicable", "Not Applicable"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
