# Generated by Django 4.2.26 on 2025-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_add_extracted_ocr_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ocr_pages_done",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
