# Generated by Django 4.2.22 on 2025-08-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
