# Generated by Django 4.2.26 on 2025-12-01 13:04

from django.db import migrations, models


def convert_hex_to_names(apps, schema_editor):
    """Convert hex color values to color names."""
    Highlight = apps.get_model("documents", "Highlight")

    # Map all known hex values (from various iterations) to color names
    hex_to_name = {
        # Original/old values
        "#FFFF00": "yellow",
        "#ffff00": "yellow",
        # -50 variants
        "#fefce8": "yellow",
        "#f7fee7": "green",
        "#eff6ff": "blue",
        "#fff7ed": "orange",
        "#fef2f2": "red",
        "#f5f3ff": "purple",
        # -200 variants
        "#fef08a": "yellow",
        "#d9f99d": "green",
        "#bfdbfe": "blue",
        "#fed7aa": "orange",
        "#fecaca": "red",
        "#e9d5ff": "purple",
        # -300 variants
        "#fde047": "yellow",
        "#bef264": "green",
        "#93c5fd": "blue",
        "#fdba74": "orange",
        "#fca5a5": "red",
        "#d8b4fe": "purple",
    }

    for hex_value, name in hex_to_name.items():
        Highlight.objects.filter(color=hex_value).update(color=name)

    # Set any remaining unrecognized values to yellow
    Highlight.objects.exclude(
        color__in=["yellow", "green", "blue", "orange", "red", "purple"]
    ).update(color="yellow")


def convert_names_to_hex(apps, schema_editor):
    """Reverse: convert color names back to hex values."""
    Highlight = apps.get_model("documents", "Highlight")

    name_to_hex = {
        "yellow": "#fde047",
        "green": "#bef264",
        "blue": "#93c5fd",
        "orange": "#fdba74",
        "red": "#fca5a5",
        "purple": "#d8b4fe",
    }

    for name, hex_value in name_to_hex.items():
        Highlight.objects.filter(color=name).update(color=hex_value)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_add_ocr_pages_done"),
    ]

    operations = [
        migrations.RunPython(convert_hex_to_names, convert_names_to_hex),
        migrations.AlterField(
            model_name="highlight",
            name="color",
            field=models.CharField(
                choices=[
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("purple", "Purple"),
                ],
                default="yellow",
                max_length=20,
            ),
        ),
    ]
