# Generated by Django 4.2.26 on 2025-12-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_highlight_color_names"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="highlight",
            name="app_documen_matter__56246d_idx",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="matter",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="slug",
        ),
    ]
