# Generated by Django 4.2.22 on 2025-09-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0009_remove_emphasis_field"),
        ("documents", "0007_alter_document_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="proceeding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matters.proceeding",
            ),
        ),
    ]
