# Generated by Django 4.2.26 on 2025-12-01 14:29

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_highlight_matter_and_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=apps.documents.models.document_upload_path
            ),
        ),
    ]
