# Generated by Django 4.2.26 on 2025-12-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_increase_file_path_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="highlight",
            old_name="title",
            new_name="slug",
        ),
    ]
