# Generated by Django 4.2.26 on 2025-12-02 14:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Move Fact model from matters app to documents app.
    Uses SeparateDatabaseAndState since both models use the same db_table.
    """

    dependencies = [
        ("matters", "0026_move_fact_from_matters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0010_document_importance_highlight_importance"),
    ]

    operations = [
        # Only change Django's state, don't touch the database
        # The table already exists as "app_fact"
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Fact",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("date", models.DateField(null=True)),
                        ("time", models.TimeField(blank=True, null=True)),
                        ("description", models.CharField(max_length=150, null=True)),
                        (
                            "color",
                            models.CharField(
                                blank=True,
                                choices=[
                                    (None, "None"),
                                    ("Blue", "Blue"),
                                    ("Gray", "Gray"),
                                    ("Green", "Green"),
                                    ("Orange", "Orange"),
                                    ("Purple", "Purple"),
                                    ("Red", "Red"),
                                    ("Yellow", "Yellow"),
                                ],
                                default=None,
                                max_length=10,
                                null=True,
                            ),
                        ),
                        (
                            "importance",
                            models.PositiveIntegerField(
                                default=5,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(10),
                                ],
                            ),
                        ),
                        (
                            "documents",
                            models.ManyToManyField(
                                blank=True, related_name="facts", to="documents.document"
                            ),
                        ),
                        (
                            "highlights",
                            models.ManyToManyField(
                                blank=True, related_name="facts", to="documents.highlight"
                            ),
                        ),
                        (
                            "matter",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="matters.matter",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "app_fact",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
