# Generated by Django 4.2.26 on 2025-12-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0026_move_fact_from_matters"),
        ("documents", "0011_move_fact_from_matters"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="facts", to="documents.label"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="highlights", to="documents.label"
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="matters.matter",
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("matter", "name"), name="unique_label_per_matter"
            ),
        ),
    ]
