# Generated by Django 4.2.26 on 2025-12-02 17:56

from django.db import migrations, models


def convert_hex_to_named_color(apps, schema_editor):
    """Convert hex colors to closest named color."""
    Label = apps.get_model("documents", "Label")

    # Map hex colors to closest named colors based on hue
    # These are rough mappings - any hex color gets mapped to the closest palette color
    for label in Label.objects.all():
        hex_color = label.color.lower()

        # Skip if already a named color
        if hex_color in ("blue", "gray", "green", "orange", "purple", "red", "yellow"):
            continue

        # Default to gray for any unrecognized format
        if not hex_color.startswith("#") or len(hex_color) != 7:
            label.color = "gray"
            label.save()
            continue

        # Parse hex to RGB
        try:
            r = int(hex_color[1:3], 16)
            g = int(hex_color[3:5], 16)
            b = int(hex_color[5:7], 16)
        except ValueError:
            label.color = "gray"
            label.save()
            continue

        # Simple hue-based classification
        max_c = max(r, g, b)
        min_c = min(r, g, b)

        # Gray detection (low saturation)
        if max_c - min_c < 30:
            label.color = "gray"
        # Red-ish (high red, low green)
        elif r > g and r > b and r - g > 50:
            if b > g + 30:
                label.color = "purple"  # More blue = purple
            else:
                label.color = "red"
        # Green-ish
        elif g > r and g > b:
            label.color = "green"
        # Blue-ish
        elif b > r and b > g:
            if r > g + 30:
                label.color = "purple"  # More red = purple
            else:
                label.color = "blue"
        # Yellow/Orange (high red and green, low blue)
        elif r > 150 and g > 150 and b < 100:
            if r > g + 30:
                label.color = "orange"
            else:
                label.color = "yellow"
        # Purple (high red and blue)
        elif r > 100 and b > 100 and g < 100:
            label.color = "purple"
        else:
            label.color = "gray"

        label.save()


def reverse_migration(apps, schema_editor):
    """No-op reverse - we can't recover original hex colors."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_labels_system"),
    ]

    operations = [
        # First convert data
        migrations.RunPython(convert_hex_to_named_color, reverse_migration),
        # Then alter the field
        migrations.AlterField(
            model_name="label",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("gray", "Gray"),
                    ("green", "Green"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                ],
                default="gray",
                max_length=20,
            ),
        ),
    ]
