# Generated by Django 4.2.26 on 2025-12-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0021_add_llm_to_conversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="chat_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("ocr_text", models.TextField(blank=True)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="case.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "matters_chat_attachment",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
