# Generated by Django 4.2.26 on 2025-12-13 21:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0027_add_proceeding_nickname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("case", "0024_add_user_to_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "importance",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="case.document"
                    ),
                ),
                (
                    "highlights",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="case.highlight"
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="case.label"
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="matters.matter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_note",
                "ordering": ["-updated_at"],
            },
        ),
    ]
