# Generated by Django 4.2.26 on 2025-12-16 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0025_add_note_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                    ("interview", "Interview"),
                    ("issue", "Issue"),
                    ("note", "Note"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="note",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
