# Generated by Django 4.2.26 on 2025-12-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0030_alter_chatattachment_options_alter_document_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_reference",
            field=models.BooleanField(
                default=False,
                help_text="Flag this conversation to be included as reference material in other conversations",
            ),
        ),
        migrations.AddField(
            model_name="historicalconversation",
            name="is_reference",
            field=models.BooleanField(
                default=False,
                help_text="Flag this conversation to be included as reference material in other conversations",
            ),
        ),
    ]
