# Generated by Django 4.2.26 on 2026-01-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0037_highlight_caselaw_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="caselaw",
            name="include_in_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcaselaw",
            name="include_in_ai",
            field=models.BooleanField(default=False),
        ),
    ]
