# Generated by Django 4.2.26 on 2026-01-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0039_remove_caselaw_structured_citation_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
