# Generated by Django 4.2.26 on 2026-01-13 17:22

from django.db import migrations


def fix_null_include_in_ai(apps, schema_editor):
    """Set include_in_ai to False for any records where it is NULL."""
    with schema_editor.connection.cursor() as cursor:
        # Fix NULL values in historicaldocument table
        cursor.execute(
            "UPDATE case_historicaldocument SET include_in_ai = FALSE WHERE include_in_ai IS NULL"
        )
        # Fix NULL values in document table (just in case)
        cursor.execute(
            "UPDATE app_document SET include_in_ai = FALSE WHERE include_in_ai IS NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0041_add_document_include_in_ai"),
    ]

    operations = [
        migrations.RunPython(fix_null_include_in_ai, migrations.RunPython.noop),
        # Ensure include_in_ai has a database-level default on both tables
        migrations.RunSQL(
            "ALTER TABLE case_historicaldocument ALTER COLUMN include_in_ai SET DEFAULT FALSE;",
            "ALTER TABLE case_historicaldocument ALTER COLUMN include_in_ai DROP DEFAULT;",
        ),
        migrations.RunSQL(
            "ALTER TABLE app_document ALTER COLUMN include_in_ai SET DEFAULT FALSE;",
            "ALTER TABLE app_document ALTER COLUMN include_in_ai DROP DEFAULT;",
        ),
    ]
