# Generated by Django 4.2.26 on 2026-02-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0043_document_include_in_ai_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caselaw",
            name="include_in_ai",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalcaselaw",
            name="include_in_ai",
            field=models.BooleanField(default=True),
        ),
    ]
