# Generated by Django 4.2.26 on 2026-02-26 16:47

from django.db import migrations, models


def migrate_gemini_3_pro(apps, schema_editor):
    Conversation = apps.get_model("case", "Conversation")
    Conversation.objects.filter(llm="gemini-3-pro").update(llm="gemini-pro-latest")


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0044_change_caselaw_include_in_ai_default"),
    ]

    operations = [
        migrations.RunPython(migrate_gemini_3_pro, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="conversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude Sonnet 4"),
                    ("claude-opus", "Claude Opus 4.5"),
                    ("gemini-flash", "Gemini 2.5 Flash"),
                    ("gemini-pro", "Gemini 2.5 Pro"),
                    ("gemini-pro-latest", "Gemini Pro (Latest)"),
                ],
                default="gemini-pro-latest",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalconversation",
            name="llm",
            field=models.CharField(
                choices=[
                    ("claude", "Claude Sonnet 4"),
                    ("claude-opus", "Claude Opus 4.5"),
                    ("gemini-flash", "Gemini 2.5 Flash"),
                    ("gemini-pro", "Gemini 2.5 Pro"),
                    ("gemini-pro-latest", "Gemini Pro (Latest)"),
                ],
                default="gemini-pro-latest",
                max_length=20,
            ),
        ),
    ]
