# Generated by Django 4.2.29 on 2026-03-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0045_use_gemini_pro_latest_alias'),
    ]

    operations = [
        # Step 1: Add new fields (keeping old include_in_ai temporarily)
        migrations.AddField(
            model_name='caselaw',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', max_length=6),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', help_text='AI context inclusion: auto (selector decides), always, or never', max_length=6),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary for intelligent context selection', null=True),
        ),
        migrations.AddField(
            model_name='historicalcaselaw',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', max_length=6),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', help_text='AI context inclusion: auto (selector decides), always, or never', max_length=6),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary for intelligent context selection', null=True),
        ),

        # Step 2: Migrate data — include_in_ai=True → "always", False → "auto"
        migrations.RunSQL(
            sql=[
                "UPDATE app_document SET ai_context = 'always' WHERE include_in_ai = TRUE;",
                "UPDATE app_document SET ai_context = 'auto' WHERE include_in_ai = FALSE;",
                "UPDATE app_case_law SET ai_context = 'always' WHERE include_in_ai = TRUE;",
                "UPDATE app_case_law SET ai_context = 'auto' WHERE include_in_ai = FALSE;",
            ],
            reverse_sql=[
                "UPDATE app_document SET include_in_ai = TRUE WHERE ai_context = 'always';",
                "UPDATE app_document SET include_in_ai = FALSE WHERE ai_context IN ('auto', 'never');",
                "UPDATE app_case_law SET include_in_ai = TRUE WHERE ai_context = 'always';",
                "UPDATE app_case_law SET include_in_ai = FALSE WHERE ai_context IN ('auto', 'never');",
            ],
        ),

        # Step 3: Remove old include_in_ai field
        migrations.RemoveField(
            model_name='caselaw',
            name='include_in_ai',
        ),
        migrations.RemoveField(
            model_name='document',
            name='include_in_ai',
        ),
        migrations.RemoveField(
            model_name='historicalcaselaw',
            name='include_in_ai',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='include_in_ai',
        ),
    ]
