# Generated by Django 4.2.29 on 2026-03-25 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matters', '0031_matter_members'),
        ('case', '0046_add_ai_context_and_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField()),
                ('state', models.CharField(blank=True, default='', max_length=20)),
                ('include_federal', models.BooleanField(default=False)),
                ('structured_query', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('refining', 'Refining'), ('refined', 'Refined'), ('searching', 'Searching'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('final_summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_queries', to='matters.matter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('case_name', models.CharField(blank=True, default='', max_length=500)),
                ('citation', models.CharField(blank=True, default='', max_length=300)),
                ('court', models.CharField(blank=True, default='', max_length=200)),
                ('date_filed', models.CharField(blank=True, default='', max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('courtlistener_url', models.URLField(blank=True, default='', max_length=500)),
                ('opinion_text', models.TextField(blank=True, default='')),
                ('relevance', models.CharField(choices=[('pending', 'Pending'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('error', 'Error')], default='pending', max_length=20)),
                ('gemini_summary', models.TextField(blank=True, default='')),
                ('status_message', models.CharField(blank=True, default='', max_length=200)),
                ('forward_citation_count', models.IntegerField(blank=True, null=True)),
                ('verify_status', models.CharField(choices=[('none', 'None'), ('verifying', 'Verifying'), ('complete', 'Complete'), ('error', 'Error')], default='none', max_length=20)),
                ('review_summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='case.researchquery')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CitationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('case_name', models.CharField(blank=True, default='', max_length=500)),
                ('citation', models.CharField(blank=True, default='', max_length=300)),
                ('court', models.CharField(blank=True, default='', max_length=200)),
                ('date_filed', models.CharField(blank=True, default='', max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('courtlistener_url', models.URLField(blank=True, default='', max_length=500)),
                ('depth', models.IntegerField(default=0)),
                ('treatment', models.CharField(blank=True, choices=[('', ''), ('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('distinguished', 'Distinguished')], default='', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='case.researchresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
