# Generated by Django 4.2.29 on 2026-03-26 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0050_reset_importance_to_normal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', help_text='AI context inclusion: auto (selector decides), always, or never', max_length=6),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary for intelligent context selection', null=True),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', help_text='AI context inclusion: auto (selector decides), always, or never', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary for intelligent context selection', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Deprecated - use ai_context instead'),
        ),
        migrations.AlterField(
            model_name='historicalcaselaw',
            name='importance',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Deprecated - use ai_context instead'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='importance',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='historicalfact',
            name='importance',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='historicalhighlight',
            name='importance',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='historicalwitness',
            name='importance',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
