# Generated by Django 4.2.29 on 2026-03-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0052_migrate_is_reference_to_ai_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_reference',
        ),
        migrations.RemoveField(
            model_name='historicalconversation',
            name='is_reference',
        ),
    ]
