# Generated by Django 4.2.29 on 2026-03-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0056_casebrief_query_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselaw',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalcaselaw',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='caselaw',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalcaselaw',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
