# Generated by Django 4.2.29 on 2026-04-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0064_conversation_vet_citations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='llm',
            field=models.CharField(choices=[('claude', 'Claude Sonnet 4.6'), ('claude-opus', 'Claude Opus 4.6'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro', 'Gemini 2.5 Pro'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='llm',
            field=models.CharField(choices=[('claude', 'Claude Sonnet 4.6'), ('claude-opus', 'Claude Opus 4.6'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro', 'Gemini 2.5 Pro'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
    ]
