# Generated by Django 4.2.30 on 2026-07-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0068_fix_renamed_matter_document_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='llm',
            field=models.CharField(choices=[('claude-opus', 'Claude Opus 4.8'), ('claude-opus-4-6', 'Claude Opus 4.6'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='llm',
            field=models.CharField(choices=[('claude-opus', 'Claude Opus 4.8'), ('claude-opus-4-6', 'Claude Opus 4.6'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
    ]
