# Generated by Django 4.2.30 on 2026-07-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0048_seed_website_practice_areas'),
        ('intakes', '0015_historicalintake_assessed_at_and_more'),
        ('case', '0069_alter_conversation_llm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='intakes.intake'),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='intake',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='intakes.intake'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='matters.matter'),
        ),
    ]
