# Generated by Django 4.2.30 on 2026-07-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0070_conversation_intake_historicalconversation_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agenda_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='agenda_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
