# Generated by Django 4.2.30 on 2026-08-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0071_conversation_agenda_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_modified',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='drive_modified',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='drive_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='drive_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
