# Generated by Django 4.2.30 on 2026-08-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0072_document_drive_file_id_document_drive_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('classic', 'Classic'), ('research', 'Research')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='research_depth',
            field=models.CharField(choices=[('quick', 'Quick'), ('standard', 'Standard'), ('deep', 'Deep')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='kind',
            field=models.CharField(choices=[('classic', 'Classic'), ('research', 'Research')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='research_depth',
            field=models.CharField(choices=[('quick', 'Quick'), ('standard', 'Standard'), ('deep', 'Deep')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='research_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='research_trail',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
