# Generated by Django 4.2.30 on 2026-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0073_conversation_kind_conversation_research_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('classic', 'Analysis'), ('research', 'Research')], default='classic', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='kind',
            field=models.CharField(choices=[('classic', 'Analysis'), ('research', 'Research')], default='classic', max_length=10),
        ),
    ]
