# Generated by Django 4.2.30 on 2026-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0076_rename_research_effort_to_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
