# Generated by Django 4.2.30 on 2026-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0078_researchresult_brief_researchresult_eval_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquery',
            name='query_variants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='hit_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='matched_variants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='triage_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
