# Generated by Django 4.2.30 on 2026-08-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0079_researchquery_query_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='researchquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refining', 'Refining'), ('refined', 'Refined'), ('searching', 'Searching'), ('selecting', 'Awaiting case selection'), ('processing', 'Processing'), ('enriching', 'Enriching'), ('synthesizing', 'Synthesizing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
