# Generated by Django 4.2.30 on 2026-08-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0080_researchresult_recommended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="page_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="page_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64, null=True
            ),
        ),
    ]
