# Generated by Django 4.2.30 on 2026-08-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_drivefoldermapping_drivematterstate'),
        ('case', '0081_document_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='drive.drivefoldermapping'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='drive_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='drive.drivefoldermapping'),
        ),
    ]
