# Generated by Django 4.2.30 on 2026-08-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0082_document_drive_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='agent_run',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='agent_run',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('classic', 'Classic'), ('research', 'Research'), ('agent', 'Agentic')], default='classic', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='kind',
            field=models.CharField(choices=[('classic', 'Classic'), ('research', 'Research'), ('agent', 'Agentic')], default='classic', max_length=10),
        ),
    ]
