# Generated by Django 4.2.30 on 2026-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0083_agent_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='llm',
            field=models.CharField(choices=[('claude-opus-5', 'Claude Opus 5'), ('claude-fable', 'Claude Fable 5'), ('claude-opus', 'Claude Opus 4.8'), ('claude-opus-4-6', 'Claude Opus 4.6'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='llm',
            field=models.CharField(choices=[('claude-opus-5', 'Claude Opus 5'), ('claude-fable', 'Claude Fable 5'), ('claude-opus', 'Claude Opus 4.8'), ('claude-opus-4-6', 'Claude Opus 4.6'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
    ]
