# Generated by Django 4.2.30 on 2026-08-24 18:41

from django.db import migrations, models
from pgvector.django import VectorExtension
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0053_unlink_complete_matters'),
        ('case', '0086_search_trigram'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='MaterialChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('note', 'Note'), ('library', 'Library note'), ('email', 'Email'), ('highlight', 'Highlight'), ('fact', 'Fact')], max_length=10)),
                ('object_id', models.IntegerField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('content_hash', models.CharField(max_length=32)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chunks', to='matters.matter')),
            ],
            options={
                'db_table': 'matters_material_chunk',
                'indexes': [models.Index(fields=['matter', 'kind'], name='matters_mat_matter__dcbf4e_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='material_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.AddConstraint(
            model_name='materialchunk',
            constraint=models.UniqueConstraint(fields=('kind', 'object_id', 'chunk_index'), name='uniq_material_chunk'),
        ),
    ]
