# Generated by Django 4.2.30 on 2026-08-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0087_material_chunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldocument',
            name='ocr_text',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='search_vector',
        ),
    ]
