# Generated by Django 4.2.26 on 2026-01-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirmProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Firm name (e.g., Craig Legal)", max_length=100
                    ),
                ),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True,
                        help_text="Legal suffix (e.g., LLC, LLP, PC)",
                        max_length=20,
                    ),
                ),
                ("address_line1", models.CharField(max_length=100)),
                ("address_line2", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="firm/")),
                (
                    "trust_caption",
                    models.TextField(
                        blank=True,
                        help_text="Explanation text shown on invoices when trust balance is displayed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firm Profile",
                "verbose_name_plural": "Firm Profile",
            },
        ),
    ]
