# Generated by Django 4.2.26 on 2026-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
