# Generated by Django 4.2.29 on 2026-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company_invoice_bcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_background',
            field=models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue')], default='gray', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_font',
            field=models.CharField(choices=[('serif', 'Serif (Noto Serif)'), ('sans', 'Sans-serif (Noto Sans)')], default='serif', max_length=10),
        ),
    ]
