# Generated by Django 4.2.29 on 2026-07-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_company_payment_background_company_payment_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_background',
        ),
        migrations.RemoveField(
            model_name='company',
            name='payment_font',
        ),
    ]
