# Generated by Django 4.2.30 on 2026-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_rename_company_firm_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='intake_email',
            field=models.EmailField(blank=True, help_text='Copied on template emails sent to intakes, and their Reply-To. Use a human inbox, not the Mailgun intake pipeline address (the pipeline would log a duplicate note).', max_length=254),
        ),
    ]
