# Generated by Django 4.2.30 on 2026-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_rename_company_firm_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='intake_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
