# Generated by Django 4.2.30 on 2026-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_firm_intake_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='quick_task_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firm',
            name='quick_task_ai_model',
            field=models.CharField(choices=[('gemini-flash', 'Gemini Flash'), ('claude-sonnet', 'Claude Sonnet')], default='gemini-flash', max_length=20),
        ),
    ]
