from django.urls import path

from apps.tasks.views import (
    clear_tasks,
    tasks_add,
    tasks_add_note,
    tasks_add_quick,
    tasks_board_bulk_move,
    tasks_board_move,
    tasks_board_show_more,
    tasks_bulk_clear_due_date,
    tasks_bulk_delete,
    tasks_bulk_set_due_date,
    tasks_bulk_set_importance,
    tasks_bulk_set_status,
    tasks_bulk_set_user,
    tasks_bulk_update,
    tasks_clear_selection,
    tasks_cycle_user,
    tasks_date,
    tasks_delete,
    tasks_delete_note,
    tasks_detail,
    tasks_detail_notes,
    tasks_edit,
    tasks_edit_note,
    tasks_filter,
    tasks_filter_default,
    tasks_filter_importance,
    tasks_filter_matter,
    tasks_filter_matter_admin,
    tasks_filter_quick,
    tasks_filter_sort,
    tasks_filter_user,
    tasks_importance,
    tasks_index,
    tasks_list,
    tasks_matter,
    tasks_panel_tab,
    tasks_select,
    tasks_select_all,
    tasks_set_status,
    tasks_set_view_mode,
    tasks_status,
    tasks_toggle_chip,
    tasks_toggle_select,
    tasks_toolbar,
    tasks_user,
)

app_name = "tasks"

urlpatterns = [
    path("", tasks_index, name="index"),
    path("tasks", tasks_select, name="select"),
    path("tasks/add", tasks_add, name="add"),
    path("tasks/add/quick", tasks_add_quick, name="add-quick"),
    path("tasks/<int:id>/edit", tasks_edit, name="edit"),
    path("tasks/<int:id>/delete", tasks_delete, name="delete"),
    path("tasks/<int:id>/task-status", tasks_status, name="task-status"),
    path(
        "tasks/<int:task_id>/task-status/<slug:status>",
        tasks_set_status,
        name="set-status",
    ),
    path(
        "tasks/<int:task_id>/task-importance/<int:importance>",
        tasks_importance,
        name="task-importance",
    ),
    path(
        "tasks/<int:task_id>/task-user/<int:user>",
        tasks_user,
        name="task-user",
    ),
    path(
        "tasks/<int:task_id>/task-matter/<int:matter_id>",
        tasks_matter,
        name="task-matter",
    ),
    path("tasks/<int:task_id>/task-date", tasks_date, name="date"),
    path("tasks/<int:id>/add-note/", tasks_add_note, name="add-note"),
    path("tasks/<int:id>/detail/", tasks_detail, name="detail"),
    path("tasks/<int:id>/detail-notes/", tasks_detail_notes, name="detail-notes"),
    path("tasks/note/<int:id>/edit/", tasks_edit_note, name="edit-note"),
    path(
        "tasks/note/<int:id>/delete/",
        tasks_delete_note,
        name="delete-note",
    ),
    path("tasks/filter/", tasks_filter, name="filter"),
    path("tasks/clear/", clear_tasks, name="clear"),
    path("tasks/list/", tasks_list, name="list"),
    path("tasks/view-mode/<str:mode>/", tasks_set_view_mode, name="view-mode"),
    path("tasks/board/move/", tasks_board_move, name="board-move"),
    path("tasks/board/bulk-move/", tasks_board_bulk_move, name="board-bulk-move"),
    path(
        "tasks/board/show-more/<str:slug>/",
        tasks_board_show_more,
        name="board-show-more",
    ),
    path("tasks/toolbar/", tasks_toolbar, name="toolbar"),
    path(
        "tasks/filter/quick/<str:quick_filter>",
        tasks_filter_quick,
        name="filter-quick",
    ),
    path(
        "tasks/filter/matter/<int:matter_id>/",
        tasks_filter_matter,
        name="filter-matter",
    ),
    path(
        "tasks/filter/matter/admin/",
        tasks_filter_matter_admin,
        name="filter-matter-admin",
    ),
    path("tasks/panel-tab/<str:tab>/", tasks_panel_tab, name="panel-tab"),
    path(
        "tasks/filter/user/<int:user_id>/",
        tasks_filter_user,
        name="filter-user",
    ),
    path(
        "tasks/cycle-user/<str:direction>/",
        tasks_cycle_user,
        name="cycle-user",
    ),
    path(
        "tasks/chips/toggle/<int:user_id>/",
        tasks_toggle_chip,
        name="toggle-chip",
    ),
    path(
        "tasks/filter/importance/<int:importance_value>/",
        tasks_filter_importance,
        name="filter-importance",
    ),
    path(
        "tasks/filter/default/",
        tasks_filter_default,
        name="filter-default",
    ),
    path(
        "tasks/filter/sort/<str:order>/",
        tasks_filter_sort,
        name="filter-sort",
    ),
    path(
        "tasks/toggle-select/<int:task_id>/",
        tasks_toggle_select,
        name="toggle-select",
    ),
    path("tasks/select-all/", tasks_select_all, name="select-all"),
    path(
        "tasks/clear-selection/",
        tasks_clear_selection,
        name="clear-selection",
    ),
    path("tasks/bulk-update/", tasks_bulk_update, name="bulk-update"),
    path(
        "tasks/bulk-set-due-date/",
        tasks_bulk_set_due_date,
        name="bulk-set-due-date",
    ),
    path(
        "tasks/bulk-set-importance/",
        tasks_bulk_set_importance,
        name="bulk-set-importance",
    ),
    path(
        "tasks/bulk-set-status/",
        tasks_bulk_set_status,
        name="bulk-set-status",
    ),
    path(
        "tasks/bulk-set-user/",
        tasks_bulk_set_user,
        name="bulk-set-user",
    ),
    path(
        "tasks/bulk-clear-due-date/",
        tasks_bulk_clear_due_date,
        name="bulk-clear-due-date",
    ),
    path("tasks/bulk-delete/", tasks_bulk_delete, name="bulk-delete"),
]
