from django.urls import path

from apps.tasks.views import (
    clear_tasks,
    tasks_add,
    tasks_add_note,
    tasks_add_quick,
    tasks_bulk_clear_due_date,
    tasks_bulk_delete,
    tasks_bulk_set_due_date,
    tasks_bulk_set_priority,
    tasks_bulk_set_status,
    tasks_bulk_set_user,
    tasks_bulk_update,
    tasks_clear_selection,
    tasks_date,
    tasks_delete,
    tasks_delete_note,
    tasks_detail,
    tasks_detail_notes,
    tasks_edit,
    tasks_edit_note,
    tasks_filter,
    tasks_filter_default,
    tasks_filter_matter,
    tasks_filter_priority,
    tasks_filter_quick,
    tasks_filter_sort,
    tasks_filter_user,
    tasks_index,
    tasks_list,
    tasks_matter,
    tasks_priority,
    tasks_select,
    tasks_select_all,
    tasks_set_status,
    tasks_status,
    tasks_toggle_select,
    tasks_user,
)

app_name = "tasks"

urlpatterns = [
    path("", tasks_index, name="index"),
    path("tasks", tasks_select, name="select"),
    path("tasks/add", tasks_add, name="add"),
    path("tasks/add/quick", tasks_add_quick, name="add-quick"),
    path("tasks/<int:id>/edit", tasks_edit, name="edit"),
    path("tasks/<int:id>/delete", tasks_delete, name="delete"),
    path("tasks/<int:id>/task-status", tasks_status, name="task-status"),
    path(
        "tasks/<int:task_id>/task-status/<str:status>",
        tasks_set_status,
        name="set-status",
    ),
    path(
        "tasks/<int:task_id>/task-priority/<int:priority>",
        tasks_priority,
        name="task-priority",
    ),
    path(
        "tasks/<int:task_id>/task-user/<int:user>",
        tasks_user,
        name="task-user",
    ),
    path(
        "tasks/<int:task_id>/task-matter/<int:matter_id>",
        tasks_matter,
        name="task-matter",
    ),
    path("tasks/<int:task_id>/task-date", tasks_date, name="date"),
    path("tasks/<int:id>/add-note/", tasks_add_note, name="add-note"),
    path("tasks/<int:id>/detail/", tasks_detail, name="detail"),
    path("tasks/<int:id>/detail-notes/", tasks_detail_notes, name="detail-notes"),
    path("tasks/note/<int:id>/edit/", tasks_edit_note, name="edit-note"),
    path(
        "tasks/note/<int:id>/delete/",
        tasks_delete_note,
        name="delete-note",
    ),
    path("tasks/filter/", tasks_filter, name="filter"),
    path("tasks/clear/", clear_tasks, name="clear"),
    path("tasks/list/", tasks_list, name="list"),
    path(
        "tasks/filter/quick/<str:quick_filter>",
        tasks_filter_quick,
        name="filter-quick",
    ),
    path(
        "tasks/filter/matter/<int:matter_id>/",
        tasks_filter_matter,
        name="filter-matter",
    ),
    path(
        "tasks/filter/user/<int:user_id>/",
        tasks_filter_user,
        name="filter-user",
    ),
    path(
        "tasks/filter/priority/<int:priority_value>/",
        tasks_filter_priority,
        name="filter-priority",
    ),
    path(
        "tasks/filter/default/",
        tasks_filter_default,
        name="filter-default",
    ),
    path(
        "tasks/filter/sort/<str:order>/",
        tasks_filter_sort,
        name="filter-sort",
    ),
    path(
        "tasks/toggle-select/<int:task_id>/",
        tasks_toggle_select,
        name="toggle-select",
    ),
    path("tasks/select-all/", tasks_select_all, name="select-all"),
    path(
        "tasks/clear-selection/",
        tasks_clear_selection,
        name="clear-selection",
    ),
    path("tasks/bulk-update/", tasks_bulk_update, name="bulk-update"),
    path(
        "tasks/bulk-set-due-date/",
        tasks_bulk_set_due_date,
        name="bulk-set-due-date",
    ),
    path(
        "tasks/bulk-set-priority/",
        tasks_bulk_set_priority,
        name="bulk-set-priority",
    ),
    path(
        "tasks/bulk-set-status/",
        tasks_bulk_set_status,
        name="bulk-set-status",
    ),
    path(
        "tasks/bulk-set-user/",
        tasks_bulk_set_user,
        name="bulk-set-user",
    ),
    path(
        "tasks/bulk-clear-due-date/",
        tasks_bulk_clear_due_date,
        name="bulk-clear-due-date",
    ),
    path("tasks/bulk-delete/", tasks_bulk_delete, name="bulk-delete"),
]
