# Generated by Django 3.2.6 on 2022-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("page", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("selected", models.IntegerField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "app_folder",
            },
        ),
    ]
