# Generated by Django 4.2.15 on 2024-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("selected", models.IntegerField(blank=True, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "app_folder",
            },
        ),
    ]
