# Generated by Django 4.1.5 on 2023-02-22 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="user_id",
        ),
        migrations.AddField(
            model_name="folder",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
