# Generated by Django 4.2.15 on 2024-08-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="user",
        ),
    ]
