# Generated by Django 4.2.15 on 2024-09-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0002_remove_folder_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folder",
            old_name="page",
            new_name="app",
        ),
    ]
