# Generated by Django 4.2.14 on 2024-07-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0002_invoice_pdf_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="approved_at",
            new_name="date_approved",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="cancelled_at",
            new_name="date_canceled",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="issue_date",
            new_name="date_issued",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="sent_at",
            new_name="date_sent",
        ),
    ]
