# Generated by Django 4.2.14 on 2024-07-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0003_rename_approved_at_invoice_date_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="pdf_file",
        ),
    ]
