# Generated by Django 4.2.17 on 2025-08-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0004_alter_credit_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="credit",
            new_name="app_invoici_matter__7a097d_idx",
            old_name="app_invoicing_matter__17a947_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="app_invoici_matter__f9543b_idx",
            old_name="app_invoicing_matter__ead650_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="app_invoici_matter__d838d0_idx",
            old_name="app_invoicing_matter__f043b6_idx",
        ),
    ]
