# Generated by Django 4.2.22 on 2025-11-23 01:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoicing",
            "0005_rename_app_invoicing_matter__17a947_idx_app_invoici_matter__7a097d_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The dollar amount from this payment applied to this invoice",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice debt being reduced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="invoicing.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="The source of the cash being applied",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="invoicing.payment",
                    ),
                ),
            ],
            options={
                "db_table": "app_invoicing_payment_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment"], name="app_invoici_payment_425137_idx"
                    ),
                    models.Index(
                        fields=["invoice"], name="app_invoici_invoice_294a20_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.UniqueConstraint(
                fields=("payment", "invoice"), name="unique_payment_invoice_application"
            ),
        ),
    ]
