# Generated by Django 4.2.14 on 2024-07-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0006_remove_invoice_date_from"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="date_to",
            new_name="date_limit",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="date_approved",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="date_canceled",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="date_sent",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                    ("CANCELED", "Canceled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
