# Generated by Django 4.2.22 on 2025-11-23 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0006_paymentapplication_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_applied",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The dollar amount from this credit applied to this invoice",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit",
                    models.ForeignKey(
                        help_text="The source credit being applied",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="invoicing.credit",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice debt being reduced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_applications",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "app_invoicing_credit_application",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["credit"], name="app_invoici_credit__29b330_idx"
                    ),
                    models.Index(
                        fields=["invoice"], name="app_invoici_invoice_7f69c2_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="creditapplication",
            constraint=models.UniqueConstraint(
                fields=("credit", "invoice"), name="unique_credit_invoice_application"
            ),
        ),
    ]
