# Generated by Django 4.2.26 on 2025-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0009_remove_unused_invoice_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent"),
                    ("DEFERRED", "Deferred"),
                    ("PAID", "Paid"),
                    ("WAIVED", "Waived"),
                    ("UNCOLLECTIBLE", "Uncollectible"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
