# Generated by Django 4.2.29 on 2026-04-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0032_matter_billable'),
        ('invoicing', '0015_alter_historicalinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matters.matter'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matters.matter'),
        ),
    ]
