# Generated by Django 4.2.29 on 2026-06-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_created_at_contact_created_by_and_more'),
        ('matters', '0036_backfill_deferred_fees'),
        ('trust', '0004_historicaltransaction_processor_and_more'),
        ('invoicing', '0025_alter_historicalpaymentrequest_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentrequest',
            name='account',
            field=models.CharField(choices=[('operating', 'Operating'), ('trust', 'Trust')], default='operating', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpaymentrequest',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='historicalpaymentrequest',
            name='trust_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trust.transaction'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='account',
            field=models.CharField(choices=[('operating', 'Operating'), ('trust', 'Trust')], default='operating', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_requests', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='trust_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trust.transaction'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='matters.matter'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['client'], name='app_invoici_client__61522f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['account'], name='app_invoici_account_2cd669_idx'),
        ),
    ]
