# Generated by Django 4.2.29 on 2026-07-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0026_historicalpaymentrequest_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransmission',
            name='kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('reminder', 'Reminder')], default='invoice', max_length=10),
        ),
    ]
