# Generated by Django 4.2.29 on 2026-07-09 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoicing', '0027_transmission_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransmission',
            name='kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('reminder', 'Reminder'), ('request', 'Payment Request')], default='invoice', max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentRequestTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('request', 'Request'), ('reminder', 'Reminder')], default='request', max_length=10)),
                ('sent_at', models.DateTimeField()),
                ('to_email', models.CharField(max_length=500)),
                ('cc_email', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='invoicing.paymentrequest')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_invoicing_payment_request_transmission',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['payment_request'], name='app_invoici_payment_898195_idx')],
            },
        ),
    ]
