# Generated by Django 4.2.29 on 2026-07-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0028_request_transmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetransmission',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_transmissions', to='invoicing.paymentrequest'),
        ),
    ]
