# Generated by Django 4.2.29 on 2026-07-07 14:03

from django.db import migrations, models
from django.db.models.functions import Left, Length

MAX_LENGTH = 150


def truncate_long_locations(apps, schema_editor):
    """Postgres refuses ALTER to varchar(150) while longer values exist, so
    trim them first. Applies to the live table and the history table alike."""
    for model_name in ("Event", "HistoricalEvent"):
        model = apps.get_model("calendar", model_name)
        model.objects.annotate(location_len=Length("location")).filter(
            location_len__gt=MAX_LENGTH
        ).update(location=Left("location", MAX_LENGTH))


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_backfill_google_synced_at'),
    ]

    operations = [
        migrations.RunPython(
            truncate_long_locations, migrations.RunPython.noop, elidable=False
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
