from django.urls import path

from apps.agenda.dash.views import dash_index
from apps.agenda.events.views import (
    events_add,
    events_api,
    events_calendar,
    events_deadline_form,
    events_deadline_modal,
    events_deadline_results,
    events_delete,
    events_edit,
    events_filter,
    events_filter_assigned,
    events_filter_matter,
    events_filter_quick,
    events_filter_sort,
    events_filter_status,
    events_index,
    events_list,
    events_quick_update,
    events_select,
    events_view_mode,
)
from apps.agenda.tasks.views import (
    clear_tasks,
    tasks_add,
    tasks_add_note,
    tasks_add_quick,
    tasks_bulk_clear_due_date,
    tasks_bulk_delete,
    tasks_bulk_set_due_date,
    tasks_bulk_set_priority,
    tasks_bulk_set_status,
    tasks_bulk_set_user,
    tasks_bulk_update,
    tasks_clear_selection,
    tasks_date,
    tasks_delete,
    tasks_delete_note,
    tasks_detail,
    tasks_edit,
    tasks_edit_note,
    tasks_filter,
    tasks_filter_default,
    tasks_filter_matter,
    tasks_filter_priority,
    tasks_filter_quick,
    tasks_filter_sort,
    tasks_filter_user,
    tasks_index,
    tasks_list,
    tasks_matter,
    tasks_priority,
    tasks_select,
    tasks_select_all,
    tasks_set_status,
    tasks_status,
    tasks_toggle_select,
    tasks_user,
)

app_name = "agenda"

urlpatterns = [
    path("", tasks_index, name="tasks-index"),
    path("agenda/tasks", tasks_select, name="tasks-select"),
    path("agenda/tasks/add", tasks_add, name="tasks-add"),
    path("agenda/tasks/add/quick", tasks_add_quick, name="tasks-add-quick"),
    path("agenda/tasks/<int:id>/edit", tasks_edit, name="tasks-edit"),
    path("agenda/tasks/<int:id>/delete", tasks_delete, name="tasks-delete"),
    path("agenda/tasks/<int:id>/task-status", tasks_status, name="tasks-task-status"),
    path(
        "agenda/tasks/<int:task_id>/task-status/<str:status>",
        tasks_set_status,
        name="tasks-set-status",
    ),
    path(
        "agenda/tasks/<int:task_id>/task-priority/<int:priority>",
        tasks_priority,
        name="tasks-task-priority",
    ),
    path(
        "agenda/tasks/<int:task_id>/task-user/<int:user>",
        tasks_user,
        name="tasks-task-user",
    ),
    path(
        "agenda/tasks/<int:task_id>/task-matter/<int:matter_id>",
        tasks_matter,
        name="tasks-task-matter",
    ),
    path("agenda/tasks/<int:task_id>/task-date", tasks_date, name="tasks-date"),
    path("agenda/tasks/<int:id>/add-note/", tasks_add_note, name="tasks-add-note"),
    path("agenda/tasks/<int:id>/detail/", tasks_detail, name="tasks-detail"),
    path("agenda/tasks/note/<int:id>/edit/", tasks_edit_note, name="tasks-edit-note"),
    path(
        "agenda/tasks/note/<int:id>/delete/",
        tasks_delete_note,
        name="tasks-delete-note",
    ),
    path("agenda/tasks/filter/", tasks_filter, name="tasks-filter"),
    path("agenda/tasks/clear/", clear_tasks, name="tasks-clear"),
    path("agenda/tasks/list/", tasks_list, name="tasks-list"),
    path(
        "activity/tasks/filter/quick/<str:quick_filter>",
        tasks_filter_quick,
        name="tasks-filter-quick",
    ),
    path(
        "agenda/tasks/filter/matter/<int:matter_id>/",
        tasks_filter_matter,
        name="tasks-filter-matter",
    ),
    path(
        "agenda/tasks/filter/user/<int:user_id>/",
        tasks_filter_user,
        name="tasks-filter-user",
    ),
    path(
        "agenda/tasks/filter/priority/<int:priority_value>/",
        tasks_filter_priority,
        name="tasks-filter-priority",
    ),
    path(
        "agenda/tasks/filter/default/",
        tasks_filter_default,
        name="tasks-filter-default",
    ),
    path(
        "agenda/tasks/filter/sort/<str:order>/",
        tasks_filter_sort,
        name="tasks-filter-sort",
    ),
    path(
        "agenda/tasks/toggle-select/<int:task_id>/",
        tasks_toggle_select,
        name="tasks-toggle-select",
    ),
    path("agenda/tasks/select-all/", tasks_select_all, name="tasks-select-all"),
    path(
        "agenda/tasks/clear-selection/",
        tasks_clear_selection,
        name="tasks-clear-selection",
    ),
    path("agenda/tasks/bulk-update/", tasks_bulk_update, name="tasks-bulk-update"),
    path(
        "agenda/tasks/bulk-set-due-date/",
        tasks_bulk_set_due_date,
        name="tasks-bulk-set-due-date",
    ),
    path(
        "agenda/tasks/bulk-set-priority/",
        tasks_bulk_set_priority,
        name="tasks-bulk-set-priority",
    ),
    path(
        "agenda/tasks/bulk-set-status/",
        tasks_bulk_set_status,
        name="tasks-bulk-set-status",
    ),
    path(
        "agenda/tasks/bulk-set-user/",
        tasks_bulk_set_user,
        name="tasks-bulk-set-user",
    ),
    path(
        "agenda/tasks/bulk-clear-due-date/",
        tasks_bulk_clear_due_date,
        name="tasks-bulk-clear-due-date",
    ),
    path("agenda/tasks/bulk-delete/", tasks_bulk_delete, name="tasks-bulk-delete"),
    path("events/", events_index, name="events-index"),
    path("events/list/", events_list, name="events-list"),
    path("events/calendar/", events_calendar, name="events-calendar"),
    path("events/api/", events_api, name="events-api"),
    path(
        "events/<int:id>/quick-update", events_quick_update, name="events-quick-update"
    ),
    path("events/view/<str:mode>", events_view_mode, name="events-view-mode"),
    path("events/select", events_select, name="events-select"),
    path("events/add", events_add, name="events-add"),
    path("events/add/<str:origin>", events_add, name="events-add-origin"),
    path(
        "events/deadline-results",
        events_deadline_results,
        name="events-deadline-results",
    ),
    path(
        "events/deadline-form",
        events_deadline_form,
        name="events-deadline-form",
    ),
    path(
        "events/deadline-calculator",
        events_deadline_modal,
        name="events-deadline-modal",
    ),
    path("events/add/<int:matter_id>", events_add, name="events-add-matter"),
    path(
        "events/add/<int:matter_id>/<str:origin>",
        events_add,
        name="events-add-matter-origin",
    ),
    path("events/<int:id>/edit", events_edit, name="events-edit"),
    path("events/<int:id>/edit/<str:origin>", events_edit, name="events-edit-origin"),
    path("events/<int:id>/delete", events_delete, name="events-delete"),
    path(
        "events/<int:id>/delete/<str:origin>",
        events_delete,
        name="events-delete-origin",
    ),
    path("events/filter/", events_filter, name="events-filter"),
    path(
        "events/filter/quick/<str:quick_filter>",
        events_filter_quick,
        name="events-filter-quick",
    ),
    path(
        "events/filter/status/",
        events_filter_status,
        {"status": ""},
        name="events-filter-status-all",
    ),
    path(
        "events/filter/status/<str:status>",
        events_filter_status,
        name="events-filter-status",
    ),
    path(
        "events/filter/sort/<str:order>",
        events_filter_sort,
        name="events-filter-sort",
    ),
    path(
        "events/filter/assigned/",
        events_filter_assigned,
        {"assigned": ""},
        name="events-filter-assigned-all",
    ),
    path(
        "events/filter/assigned/<str:assigned>",
        events_filter_assigned,
        name="events-filter-assigned",
    ),
    path(
        "events/filter/matter/",
        events_filter_matter,
        {"matter": ""},
        name="events-filter-matter-all",
    ),
    path(
        "events/filter/matter/<str:matter>",
        events_filter_matter,
        name="events-filter-matter",
    ),
    path("dash/", dash_index, name="dash-index"),
]
