from django.urls import path

from apps.documents.views import (
    add_highlight,
    add_label,
    add_label_to,
    bulk_files_update,
    clear_file_selection,
    delete_highlight,
    delete_label,
    document_category,
    document_date,
    document_importance,
    document_proceeding,
    document_viewer,
    download_document,
    edit_highlight,
    edit_label,
    fact_add_source,
    fact_importance,
    fact_remove_source,
    fact_sources_modal,
    fact_sources_search,
    file_row,
    files_add,
    files_delete,
    files_edit,
    files_filter,
    files_filter_category,
    files_filter_keyword,
    files_filter_label,
    files_list,
    files_sort,
    get_proceedings_and_labels,
    highlight_importance,
    highlight_link,
    highlights_filter,
    highlights_filter_default,
    highlights_filter_document,
    highlights_filter_keyword,
    highlights_filter_sort,
    highlights_for_document,
    highlights_index,
    highlights_list,
    index,
    labels_apply_modal,
    labels_filter,
    labels_index,
    labels_list,
    labels_search,
    labels_sort,
    ocr_badge,
    ocr_status,
    remove_label_from,
    retry_ocr,
    select_matter,
    serve_document,
    timeline_add,
    timeline_delete,
    timeline_edit,
    timeline_edit_description,
    timeline_filter,
    timeline_filter_keyword,
    timeline_index,
    timeline_list,
    timeline_pdf,
    timeline_print,
    timeline_sort,
    timeline_update_description,
    toggle_file_select,
)

app_name = "documents"

urlpatterns = [
    # Files (file list subtab)
    path("files/", index, name="index"),
    path("files/list/", files_list, name="files-list"),
    path("files/select-matter/<int:matter_id>/", select_matter, name="select-matter"),
    path("files/add/", files_add, name="files-add"),
    path("files/add/<int:matter_id>/", files_add, name="files-add-with-matter"),
    path("files/edit/<int:document_id>/", files_edit, name="files-edit"),
    path("files/delete/<int:document_id>/", files_delete, name="files-delete"),
    path("files/filter/", files_filter, name="files-filter"),
    path(
        "files/filter/label/<int:label_id>/",
        files_filter_label,
        name="files-filter-label",
    ),
    path(
        "files/filter/category/",
        files_filter_category,
        name="files-filter-category-clear",
    ),
    path(
        "files/filter/category/<str:category>/",
        files_filter_category,
        name="files-filter-category",
    ),
    path(
        "files/filter/keyword/",
        files_filter_keyword,
        name="files-filter-keyword",
    ),
    path("files/sort/<str:order>/", files_sort, name="files-sort"),
    path("files/download/<int:document_id>/", download_document, name="files-download"),
    # Inline editing
    path(
        "files/<int:document_id>/date/",
        document_date,
        name="file-date",
    ),
    path(
        "files/<int:document_id>/category/<str:category>/",
        document_category,
        name="file-category",
    ),
    path(
        "files/<int:document_id>/proceeding/<int:proceeding_id>/",
        document_proceeding,
        name="file-proceeding",
    ),
    path(
        "files/<int:document_id>/importance/<int:importance>/",
        document_importance,
        name="file-importance",
    ),
    path(
        "files/get-proceedings-and-labels/",
        get_proceedings_and_labels,
        name="get-proceedings-and-labels",
    ),
    path("files/bulk-update/", bulk_files_update, name="files-bulk-update"),
    path(
        "files/toggle-select/<int:document_id>/",
        toggle_file_select,
        name="files-toggle-select",
    ),
    path("files/clear-selection/", clear_file_selection, name="files-clear-selection"),
    path("files/row/<int:document_id>/", file_row, name="file-row"),
    path("files/ocr-badge/<int:document_id>/", ocr_badge, name="ocr-badge"),
    # Labels
    path("documents/labels/", labels_index, name="labels-index"),
    path("documents/labels/list/", labels_list, name="labels-list"),
    path("documents/labels/add/", add_label, name="add-label"),
    path("documents/labels/edit/<int:label_id>/", edit_label, name="edit-label"),
    path("documents/labels/delete/<int:label_id>/", delete_label, name="delete-label"),
    path("documents/labels/filter/", labels_filter, name="filter-labels"),
    path("documents/labels/sort/<str:order>/", labels_sort, name="sort-labels"),
    # Label application (to documents/highlights/facts)
    path(
        "documents/labels/apply/<str:object_type>/<int:object_id>/",
        labels_apply_modal,
        name="labels-apply-modal",
    ),
    path(
        "documents/labels/search/<str:object_type>/<int:object_id>/",
        labels_search,
        name="labels-search",
    ),
    path(
        "documents/labels/add-to/<str:object_type>/<int:object_id>/",
        add_label_to,
        name="add-label-to",
    ),
    path(
        "documents/labels/remove-from/<str:object_type>/<int:object_id>/",
        remove_label_from,
        name="remove-label-from",
    ),
    # PDF Viewer
    path("files/view/<int:document_id>/", document_viewer, name="viewer"),
    path("files/serve/<int:document_id>/", serve_document, name="serve"),
    # OCR endpoints
    path("files/ocr-status/<int:document_id>/", ocr_status, name="ocr-status"),
    path("files/retry-ocr/<int:document_id>/", retry_ocr, name="retry-ocr"),
    # Highlight endpoints
    path(
        "files/<int:document_id>/highlights/add/",
        add_highlight,
        name="add-highlight",
    ),
    path(
        "documents/highlights/<int:highlight_id>/edit/",
        edit_highlight,
        name="edit-highlight",
    ),
    path(
        "documents/highlights/<int:highlight_id>/delete/",
        delete_highlight,
        name="delete-highlight",
    ),
    path(
        "documents/highlights/<int:highlight_id>/importance/<int:importance>/",
        highlight_importance,
        name="highlight-importance",
    ),
    path(
        "documents/highlights/<int:highlight_id>/",
        highlight_link,
        name="highlight-link",
    ),
    # Highlights subapp
    path("documents/highlights/", highlights_index, name="highlights-index"),
    path(
        "documents/highlights/for/<int:document_id>/",
        highlights_for_document,
        name="highlights-for-document",
    ),
    path("documents/highlights/list/", highlights_list, name="highlights-list"),
    path("documents/highlights/filter/", highlights_filter, name="highlights-filter"),
    path(
        "documents/highlights/filter/document/",
        highlights_filter_document,
        name="highlights-filter-document",
    ),
    path(
        "documents/highlights/filter/document/<int:document_id>/",
        highlights_filter_document,
        name="highlights-filter-document",
    ),
    path(
        "documents/highlights/filter/keyword/",
        highlights_filter_keyword,
        name="highlights-filter-keyword",
    ),
    path(
        "documents/highlights/filter/sort/<str:order>/",
        highlights_filter_sort,
        name="highlights-filter-sort",
    ),
    path(
        "documents/highlights/filter/default/",
        highlights_filter_default,
        name="highlights-filter-default",
    ),
    # Timeline subapp
    path("documents/timeline/", timeline_index, name="timeline-index"),
    path("documents/timeline/list/", timeline_list, name="timeline-list"),
    path("documents/timeline/filter/", timeline_filter, name="timeline-filter"),
    path(
        "documents/timeline/filter/keyword/",
        timeline_filter_keyword,
        name="timeline-filter-keyword",
    ),
    path("documents/timeline/sort/<str:order>/", timeline_sort, name="timeline-sort"),
    path("documents/timeline/add/", timeline_add, name="timeline-add"),
    path("documents/timeline/<int:fact_id>/edit/", timeline_edit, name="timeline-edit"),
    path(
        "documents/timeline/<int:fact_id>/delete/",
        timeline_delete,
        name="timeline-delete",
    ),
    path("documents/timeline/print/", timeline_print, name="timeline-print"),
    path("documents/timeline/pdf/", timeline_pdf, name="timeline-pdf"),
    path(
        "documents/timeline/<int:fact_id>/edit-description/",
        timeline_edit_description,
        name="timeline-edit-description",
    ),
    path(
        "documents/timeline/<int:fact_id>/update-description/",
        timeline_update_description,
        name="timeline-update-description",
    ),
    path(
        "documents/timeline/<int:fact_id>/sources/",
        fact_sources_modal,
        name="fact-sources",
    ),
    path(
        "documents/timeline/<int:fact_id>/sources/search/",
        fact_sources_search,
        name="fact-sources-search",
    ),
    path(
        "documents/timeline/<int:fact_id>/sources/add/",
        fact_add_source,
        name="fact-add-source",
    ),
    path(
        "documents/timeline/<int:fact_id>/sources/remove/",
        fact_remove_source,
        name="fact-remove-source",
    ),
    path(
        "documents/timeline/<int:fact_id>/importance/<int:importance>/",
        fact_importance,
        name="fact-importance",
    ),
]
