# Generated by Django 3.2.6 on 2022-11-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                ("date_start", models.DateField(null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("firm", models.CharField(max_length=50, null=True)),
                ("firm_file_no", models.CharField(max_length=500, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=50, null=True)),
                ("practice_area", models.CharField(max_length=50, null=True)),
                ("hourly_rate", models.IntegerField(blank=True, null=True)),
                ("firm_rate", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "app_matter",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "app_matter_role",
            },
        ),
        migrations.CreateModel(
            name="SettlementEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("date", models.DateField(null=True)),
                ("medium", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(max_length=150, null=True)),
                ("amount", models.CharField(max_length=50, null=True)),
                ("notes", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "db_table": "app_settlement",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matters.matter"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="matters.role"
                    ),
                ),
            ],
            options={
                "db_table": "app_matter_relationship",
            },
        ),
        migrations.CreateModel(
            name="Proceeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("date_filed", models.DateField(null=True)),
                ("forum", models.CharField(max_length=150, null=True)),
                ("case_number", models.CharField(max_length=50, null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "db_table": "app_proceeding",
            },
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("date", models.DateField(null=True)),
                ("description", models.CharField(max_length=150, null=True)),
                ("citation", models.CharField(blank=True, max_length=155, null=True)),
                ("emphasis", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "matter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "db_table": "app_fact",
            },
        ),
    ]
