# Generated by Django 4.2.11 on 2024-07-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matter",
            name="firm_rate",
        ),
        migrations.RemoveField(
            model_name="matter",
            name="hourly_rate",
        ),
    ]
