# Generated by Django 4.1.5 on 2023-02-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_folder"),
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="contacts",
            field=models.ManyToManyField(
                through="matters.Relationship", to="contacts.contact"
            ),
        ),
    ]
