# Generated by Django 4.2.17 on 2024-12-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceeding",
            name="primary",
            field=models.BooleanField(default=False),
        ),
    ]
