# Generated by Django 4.2.16 on 2025-03-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0002_proceeding_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
