# Generated by Django 4.2.14 on 2024-07-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0002_remove_matter_firm_rate_remove_matter_hourly_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matter",
            old_name="ref_no",
            new_name="client_reference_id",
        ),
        migrations.RenameField(
            model_name="matter",
            old_name="firm_file_no",
            new_name="clio_matter_id",
        ),
    ]
