# Generated by Django 4.2.22 on 2025-08-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0003_fact_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name='matter',
            old_name='description',
            new_name='work_status',
        ),
    ]
