# Generated by Django 5.0.4 on 2024-06-14 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contact_client_status"),
        ("matters", "0003_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_matters",
                to="contacts.contact",
            ),
        ),
    ]
