# Generated by Django 4.2.22 on 2025-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0005_rename_fact_citation_to_citations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fact",
            name="citations",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
