# Generated by Django 4.2.22 on 2025-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0006_alter_fact_citations"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("Red", "Red"),
                    ("Blue", "Blue"),
                    ("Yellow", "Yellow"),
                    ("Green", "Green"),
                    ("Purple", "Purple"),
                    ("Orange", "Orange"),
                    ("Gray", "Gray"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
