# Generated by Django 4.2.22 on 2025-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0008_migrate_emphasis_to_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fact",
            name="emphasis",
        ),
        migrations.AlterField(
            model_name="fact",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("Blue", "Blue"),
                    ("Gray", "Gray"),
                    ("Green", "Green"),
                    ("Orange", "Orange"),
                    ("Purple", "Purple"),
                    ("Red", "Red"),
                    ("Yellow", "Yellow"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
