# Generated by Django 4.2.22 on 2025-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0009_remove_emphasis_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
