# Generated by Django 4.2.26 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0010_matter_description"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(fields=["status"], name="app_matter_status_2f2f4b_idx"),
        ),
        migrations.AddIndex(
            model_name="matter",
            index=models.Index(fields=["client"], name="app_matter_client__50b440_idx"),
        ),
    ]
