# Generated by Django 4.2.26 on 2025-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0020_cleanup_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
