# Generated by Django 4.2.26 on 2025-11-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0021_add_is_active_to_group_and_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matters.group"
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="matters.role"
            ),
        ),
    ]
