# Generated by Django 4.2.26 on 2025-12-02 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0024_add_fact_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="importance",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
