# Generated by Django 4.2.26 on 2025-12-02 14:42

from django.db import migrations


class Migration(migrations.Migration):
    """
    Move Fact model from matters app to documents app.
    Uses SeparateDatabaseAndState since both models use the same db_table.
    """

    dependencies = [
        ("matters", "0025_fact_importance"),
    ]

    # We need documents migration to run first to create the model there
    run_before = [
        ("documents", "0011_move_fact_from_matters"),
    ]

    operations = [
        # Only change Django's state, don't touch the database
        # The table stays as "app_fact"
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Fact",
                ),
            ],
            database_operations=[],
        ),
    ]
