# Generated by Django 4.2.26 on 2025-12-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0026_move_fact_from_matters"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceeding",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="matter",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
