# Generated by Django 4.2.26 on 2026-02-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0028_group_created_at_group_created_by_group_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmatter",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="matter",
            name="firm",
        ),
    ]
