# Generated by Django 4.2.26 on 2026-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0029_remove_historicalmatter_firm_remove_matter_firm"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmatter",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="matter",
            name="jurisdiction",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
