# Generated by Django 4.2.29 on 2026-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0031_matter_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='matter',
            index=models.Index(fields=['billable'], name='app_matter_billabl_3d302c_idx'),
        ),
    ]
