# Generated by Django 4.2.29 on 2026-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0043_backfill_client_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='uncategorized_claimed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='uncategorized_claimed',
            field=models.BooleanField(default=True),
        ),
    ]
