# Generated by Django 4.2.29 on 2026-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0044_historicalmatter_uncategorized_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='report_include_unclaimed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='report_include_unclaimed',
            field=models.BooleanField(default=True),
        ),
    ]
