# Generated by Django 4.2.29 on 2026-07-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0045_historicalmatter_report_include_unclaimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='report_group_by_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='report_show_entries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='report_group_by_category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='report_show_entries',
            field=models.BooleanField(default=True),
        ),
    ]
