# Generated by Django 4.2.29 on 2026-07-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0046_historicalmatter_report_group_by_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='report_reclaim_comp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matter',
            name='report_reclaim_comp',
            field=models.BooleanField(default=False),
        ),
    ]
