# Generated by Django 4.2.30 on 2026-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0048_seed_website_practice_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='gmail_label_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalmatter',
            name='gmail_label_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='gmail_label_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='gmail_label_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
