# Generated by Django 4.2.30 on 2026-08-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0049_historicalmatter_gmail_label_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproceeding',
            name='drive_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='drive_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='proceeding',
            constraint=models.UniqueConstraint(condition=models.Q(('drive_folder__isnull', False)), fields=('matter', 'drive_folder'), name='unique_proceeding_drive_folder_per_matter'),
        ),
    ]
