# Generated by Django 4.2.30 on 2026-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0050_historicalproceeding_drive_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
