# Generated by Django 4.2.30 on 2026-08-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0004_convert_legacy_links"),
        ('matters', '0051_matter_drive_folder_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proceeding',
            name='unique_proceeding_drive_folder_per_matter',
        ),
        migrations.RemoveField(
            model_name='historicalproceeding',
            name='drive_folder',
        ),
        migrations.RemoveField(
            model_name='proceeding',
            name='drive_folder',
        ),
    ]
