# Generated by Django 4.1.5 on 2024-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="description",
        ),
    ]
