# Generated by Django 4.2.15 on 2024-09-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="priority",
            new_name="urgent",
        ),
    ]
