# Generated by Django 4.2.15 on 2024-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_rename_priority_task_urgent"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=5),
        ),
    ]
