# Generated by Django 4.1.5 on 2024-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_rename_title_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.BooleanField(default=False),
        ),
    ]
