# Generated by Django 4.2.16 on 2025-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="term",
            field=models.CharField(
                choices=[("Current", "Current"), ("Long Term", "Long Term")],
                default="Current",
                max_length=20,
            ),
        ),
    ]
