# Generated by Django 4.2.16 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_task_term"),
    ]

    operations = [
        # Rename the field from term to focus
        migrations.RenameField(
            model_name='task',
            old_name='term',
            new_name='focus',
        ),
        # Update the field definition with new field name but same choices
        migrations.AlterField(
            model_name='task',
            name='focus',
            field=models.CharField(
                choices=[("Current", "Current"), ("Long Term", "Long Term")],
                default="Current",
                max_length=20,
            ),
        ),
    ]