# Generated by Django 4.2.26 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_task_custom_order_alter_task_priority"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["matter"], name="app_event_matter__bd27b8_idx"),
        ),
    ]
