# Generated by Django 4.2.26 on 2025-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0013_standardize_charfield_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
