# Generated by Django 4.2.26 on 2025-11-27 22:14

from django.db import migrations


def delete_complete_tasks_without_date(apps, schema_editor):
    Task = apps.get_model("agenda", "Task")
    Task.objects.filter(status="Complete", date_completed__isnull=True).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0014_add_date_completed_to_task"),
    ]

    operations = [
        migrations.RunPython(delete_complete_tasks_without_date, noop),
    ]
