# Generated by Django 4.2.26 on 2025-11-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agenda", "0016_add_task_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTaskNoteView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agenda.task"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_user_task_note_view",
                "indexes": [
                    models.Index(
                        fields=["user", "task"], name="app_user_ta_user_id_1e885f_idx"
                    )
                ],
                "unique_together": {("user", "task")},
            },
        ),
    ]
