# Generated by Django 4.2.26 on 2025-11-28 20:40

from django.db import migrations


def update_event_status(apps, schema_editor):
    Event = apps.get_model("agenda", "Event")
    Event.objects.filter(status="Completed").update(status="Complete")


def reverse_event_status(apps, schema_editor):
    Event = apps.get_model("agenda", "Event")
    Event.objects.filter(status="Complete").update(status="Completed")


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0017_add_user_task_note_view"),
    ]

    operations = [
        migrations.RunPython(update_event_status, reverse_event_status),
    ]
