# Generated by Django 4.2.28 on 2026-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_add_assigned_to_and_optional_matter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
