# Generated by Django 4.2.28 on 2026-03-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query_text", models.TextField()),
                (
                    "jurisdiction",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "jurisdiction_display",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("searching", "Searching"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("final_summary", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("case_name", models.CharField(blank=True, default="", max_length=500)),
                ("citation", models.CharField(blank=True, default="", max_length=300)),
                ("court", models.CharField(blank=True, default="", max_length=200)),
                ("date_filed", models.CharField(blank=True, default="", max_length=20)),
                ("cluster_id", models.IntegerField(blank=True, null=True)),
                ("snippet", models.TextField(blank=True, default="")),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "courtlistener_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("opinion_text", models.TextField(blank=True, default="")),
                (
                    "relevance",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gemini_summary", models.TextField(blank=True, default="")),
                (
                    "status_message",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="research.researchquery",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
