# Generated by Django 4.2.28 on 2026-03-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchquery",
            name="jurisdiction",
        ),
        migrations.RemoveField(
            model_name="researchquery",
            name="jurisdiction_display",
        ),
        migrations.AddField(
            model_name="researchquery",
            name="include_federal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchquery",
            name="state",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="researchquery",
            name="structured_query",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="researchquery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("refining", "Refining"),
                    ("searching", "Searching"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
