# Generated by Django 4.2.29 on 2026-03-13 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_remove_researchquery_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresult',
            name='forward_citation_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchresult',
            name='verify_status',
            field=models.CharField(choices=[('none', 'None'), ('verifying', 'Verifying'), ('complete', 'Complete'), ('error', 'Error')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('refining', 'Refining'), ('refined', 'Refined'), ('searching', 'Searching'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CitationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('case_name', models.CharField(blank=True, default='', max_length=500)),
                ('citation', models.CharField(blank=True, default='', max_length=300)),
                ('court', models.CharField(blank=True, default='', max_length=200)),
                ('date_filed', models.CharField(blank=True, default='', max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('courtlistener_url', models.URLField(blank=True, default='', max_length=500)),
                ('depth', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='research.researchresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
