name: Linting and Testing Pull Requests

on:
  pull_request:
    branches: [ "dev" ]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  ENV: ${{ vars.ENV }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  SITE_NAME: ${{ vars.SITE_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  ADMINS: ${{ vars.ADMINS }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  SERVER_EMAIL: ${{ secrets.SERVER_EMAIL }}
  DIGITAL_OCEAN_REGION_NAME: ${{ secrets.DIGITAL_OCEAN_REGION_NAME }}
  DIGITAL_OCEAN_ENDPOINT_URL: ${{ secrets.DIGITAL_OCEAN_ENDPOINT_URL }}
  DIGITAL_OCEAN_BUCKET_NAME: ${{ secrets.DIGITAL_OCEAN_BUCKET_NAME }}
  DIGITAL_OCEAN_ACCESS_KEY_ID: ${{ secrets.DIGITAL_OCEAN_ACCESS_KEY_ID }}
  DIGITAL_OCEAN_SECRET_ACCESS_KEY: ${{ secrets.DIGITAL_OCEAN_SECRET_ACCESS_KEY }}

jobs:
  lint-and-test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: uv sync

      - name: Install Node dependencies
        run: npm install

      - name: Run migrations
        run: python manage.py migrate

      - name: Lint code
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest -n auto
