# Generated by Django 4.2.30 on 2026-08-01 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveRecordTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_drive_record_tombstone',
            },
        ),
        migrations.AddField(
            model_name='drivesyncstate',
            name='missing_record_folders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
