# Generated by Django 4.2.30 on 2026-08-21 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0051_matter_drive_folder_id'),
        ('drive', '0002_driverecordtombstone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivesyncstate',
            name='missing_record_folders',
        ),
        migrations.CreateModel(
            name='DriveMatterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmapped_folders', models.JSONField(blank=True, default=list)),
                ('folder_missing', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_state', to='matters.matter')),
            ],
            options={
                'db_table': 'app_drive_matter_state',
            },
        ),
        migrations.CreateModel(
            name='DriveFolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_path', models.CharField(max_length=1024)),
                ('category', models.CharField(choices=[('Correspondence', 'Correspondence'), ('Discovery', 'Discovery'), ('Evidence', 'Evidence'), ('Record', 'Record')], max_length=20)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_folder_mappings', to='matters.matter')),
                ('proceeding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_folder_mappings', to='matters.proceeding')),
            ],
            options={
                'db_table': 'app_drive_folder_mapping',
            },
        ),
        migrations.AddConstraint(
            model_name='drivefoldermapping',
            constraint=models.UniqueConstraint(condition=models.Q(('folder_id__isnull', False)), fields=('folder_id',), name='unique_drive_folder_mapping_folder_id'),
        ),
        migrations.AddConstraint(
            model_name='drivefoldermapping',
            constraint=models.UniqueConstraint(condition=models.Q(('folder_id__isnull', True)), fields=('matter', 'folder_path'), name='unique_drive_folder_mapping_legacy_path'),
        ),
        migrations.AddConstraint(
            model_name='drivefoldermapping',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 'Record'), ('proceeding__isnull', False)), ('category', 'Discovery'), models.Q(('category__in', ['Correspondence', 'Evidence']), ('proceeding__isnull', True)), _connector='OR'), name='drive_folder_mapping_proceeding_rule'),
        ),
    ]
