# Generated by Django 4.2.30 on 2026-07-30 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matters', '0049_historicalmatter_gmail_label_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(blank=True, max_length=32, null=True)),
                ('missing_labels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_gmail_sync_state',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_id', models.CharField(max_length=32)),
                ('thread_id', models.CharField(db_index=True, max_length=32)),
                ('label_id', models.CharField(blank=True, max_length=64)),
                ('sender', models.CharField(blank=True, max_length=500)),
                ('recipients', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('date', models.DateTimeField(db_index=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_source', models.CharField(choices=[('plain', 'Plain text'), ('html', 'HTML')], default='plain', max_length=10)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('importance', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('ai_context', models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', max_length=6)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='matters.matter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_email',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['matter', 'thread_id'], name='app_email_matter__5495ae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('matter', 'gmail_id'), name='unique_email_per_matter'),
        ),
    ]
