# Generated by Django 4.2.30 on 2026-07-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0071_conversation_agenda_user_and_more'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='body_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='email',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='case.document'),
        ),
    ]
