# Generated by Django 4.2.30 on 2026-07-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email_body_html_email_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attachments',
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_attachment_id', models.TextField(blank=True)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('extract_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('no_text_layer', 'No text layer (scanned)'), ('unsupported', 'Unsupported type'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='mail.email')),
            ],
            options={
                'db_table': 'app_email_attachment',
                'ordering': ['id'],
            },
        ),
    ]
