# Generated by Django 4.2.30 on 2026-07-31 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0003_remove_email_attachments_emailattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('token', models.TextField()),
                ('history_id', models.CharField(blank=True, max_length=32, null=True)),
                ('missing_labels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_gmail_account',
            },
        ),
        migrations.RemoveConstraint(
            model_name='email',
            name='unique_email_per_matter',
        ),
        migrations.AddField(
            model_name='email',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=998),
        ),
        migrations.AddField(
            model_name='gmailaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail.gmailaccount'),
        ),
        # Manually moved below the account AddField: the autodetector emitted
        # the constraint before the field it references existed.
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('account', 'matter', 'gmail_id'), name='unique_email_per_account_matter'),
        ),
    ]
